### ISSUE TITLE
Requesting New Block Mode with Tor Browser fingerprint

### ISSUE THREAD

**Issue by rahulprabhakar** [kkapsner/CanvasBlocker#125]
I wud like to suggest providing additional block mode to return Tor Browser fingerprint as a canvas readout instead of returning actual / fake value or U cud also provide feature wherein user cud manually set desired canvas hash meant to be returned on readout.

I managed to setup firefox to achieve following result on https://www.panopticlick.eff.org
"Your browser fingerprint is nearly unique"

Only difference between firefox result and tor browser result was the canvas hash fingerprint.
In firefox i am using Canvas Blocker with block readout.

Somehow if i cud return Tor Browser canvas hash using canvas blocker then even firefox setup wud become non-unique.

**Comment by kkapsner** [comment]
I would have to built a complete canvas randering engine that does not use installed fonts or the GPU by myself in the addon. First I do not have the resources (time and knowledge) to do this and secondly this would be extremly slow and not usable.

I do not see how setting a "hash" (which is btw technically not possible because the content of the hash is dependent on the site that creates the fingerprint) manually would increase the protection in any way. You can only set the values the persitent random number generator uses for each domain seperately in about:config if you realy want to...

PS: getting a unique hash is not a bad thing if it does not stay constant. That is the whole idea behind the fake readout mode.
