### ISSUE TITLE
not getting icon

### ISSUE THREAD

**Issue by amrgul** [kkapsner/CanvasBlocker#129]
On waterfox I don't get you extension's original icon but just green general icon.

**Comment by kkapsner** [comment]
Which version are you using? How did you install it? Via AMO or did you download the XPI from github?

**Comment by amrgul** [comment]
hi, it's latest version of addon and waterfox 55.0.2 installed from mozilla's addon page.

**Comment by spodermenpls** [comment]
I deactivated the add-on section's extended access to AMO by setting "extensions.getAddons.cache.enabled" to false, to switch off the telemetry transfer, since then only the green placeholder icon gets displayed as well (in opposite to most other add-ons I use). Is the CB icon not part of the package or maybe wrongly linked?

**Comment by kkapsner** [comment]
It seems I accidentally excluded the icon from the packaging... but this issue will be solved with the next version (a WebExtension).
