### ISSUE TITLE
Display alerts using notification bar (not JS popup)

### ISSUE THREAD

**Issue by nodiscc** [kkapsner/CanvasBlocker#14]
Thanks, very promising addon.  This addon is a good recommendation for https://github.com/DIVERSIFY-project/amiunique/issues/2 (https://amiunique.org/ - open source browser fingerprinting tool)

The popup notification is _very_ intrusive though, having it grab all input on every page load is annoying. Do you think you could use a notification box instead? (https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/notificationbox, click-to-play-like notification) A simple bar like this should do the trick:

`Blocked <canvas> readout to https://someserver/path/.../576578.js [Keep blocking] [Allow]`

**Comment by kkapsner** [comment]
I also do not like the popup notifications. But I have to stop the page from executing the code until the permissions are granted or denied. This is the security model up to now.

If I change to a notification box I have to deny everything at the first load of the page and do a refresh if the user clicks "allow". This could work but could require a lot of reloads...

But I think a special flavour for the "fake readout"-mode could do a good job. Everytime the readout is faked a notification box is opened and the user can disable the faking for that particular page.

I really disfavour the "block ..." modes because they tend to break legitimate JS applications. I think the "fake" approach is the right way to go.

**Comment by nodiscc** [comment]
@kkapsner Yes I agree having to reload the page on every "allow this readout" action would be cumbersome.

The fake readout idea is interesting. So you'd have a whitelist for pages that are allowed to do canvas readouts? Why not make it domain-wide? Eg

`Sent a fake <canvas> readout to some.domain.org [Keep blocking] [Allow readouts to this domain]`

**Comment by kkapsner** [comment]
The white list is already in place. I "only" have to implement the notification...

**Comment by kkapsner** [comment]
The new branch https://github.com/kkapsner/CanvasBlocker/tree/notificationOnFakeReadout implements notifications.

Please test.

**Comment by kkapsner** [comment]
Notifications are now part of the latest release.

**Comment by facetoe** [comment]
Hello, I'm a bit confused about these popups. What happens if I click ignorelistDomain, ignore URL or ignore domain?

**Comment by asdgfd** [comment]
Why are we suddenly being notified for every single website that CB fakes a canvas for? Where is the way to disable notifications? Having a constant yellow bar thicker than my tabs and navigation toolbar on firefox is rather annoying? Am I supposed to click the X to close it every single time I navigate a page on 2/3rds of the websites I visit? Horribly intrusive change. It was better when CB just did its job and didn't fill my screen with a fraken notification bar every time I use a website.

**Comment by facetoe** [comment]
I agree with @asdgfd, the popup is annoying.

**Comment by kkapsner** [comment]
@ facetoe: There was an error in the translation file now the labels of the popups should be right. If you "ignore" a domain the notificatios will not be shown for this domain. I added github there...

@asdgfd: In the latest version here on github I added a preference to disable the notifications.

**Comment by facetoe** [comment]
Awesome, thanks. I'll give the new version a go. BTW, thanks for your work on this, it's much appreciated.

**Comment by kkapsner** [comment]
You're welcome.

I appreciate your feedback and input.
