### ISSUE TITLE
unnecessary IPv6 lookups with 0.4.3c

### ISSUE THREAD

**Issue by kairaven** [kkapsner/CanvasBlocker#171]
After installing 0.4.3c i get a lot of ipv6 lookups as seen in my privoxy log:
10:40:10 016 Header: scan: CONNECT [::]:443 HTTP/1.1
10:40:10 016 Header: scan: Host: [::]:443
10:40:10 016 Crunch: Forwarding failed: [::]:443

and in my tor log:
Refusing to connect to IPv6 address :: because Port has NoIPv6Traffic set

Disabling CanvasBlocker or installing 0.4.3b stops the lookups. Because i have not enabled IPv6 on the OS level or in software and i don't want to use IPv6, i don't want to use it with CanvasBlocker ;)

# Environment
* CanvasBlocker Version used: 0.4.3b and 0.4.3c
* Firefox version incl. 32- or 64-bit: 57 64-bit
* Operating System: Debian Linux Stretch

**Comment by kkapsner** [comment]
Thanks for the input. To be hones: I do not want this as well but I have to do this. This IPv6-address is defined as not specified (https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml) and should not lead to any traffic.

Some background why this is necessary: since the transition to WebExtensions an addon can no longer load the settings the user made in a synchronous way. So it is not guaranteed that the settings are loaded before the web page wants to fingerprint you. Therefore I need a way to pause the execution a bit until the settings are present. The only way I know it so make a fake network call. And this is the one you see. It does not matter if the request is successful or not. So you do not need to enable IPv6 anywhere.

PS: Firefox 59 finally provides a way to load the settings synchronous.

**Comment by kairaven** [comment]
Ok, i see. Thanks for the explanation and info :)
