### ISSUE TITLE
Requests to https://[::]/

### ISSUE THREAD

**Issue by pacocc** [kkapsner/CanvasBlocker#179]
On installing CanvasBlocker my web logs began showing numerous requests to https://[::]/.
Bug #171 indicates this is a necessary hack when dealing with WebExtensions to "pause the execution a bit until (user made?) settings are present"  There are several problems with this solution:

 1) it appears to violate RFC 4291

 2) it is unnecessary under -esr, icedove and other firefox forks that do not use WebExtensions, and

 3) it can cause (proxy server) socket tables to fill with hung requests that do not timeout (possibly an OS bug)

A partial solution would be to predicate the URL request on a firefox version number check.

**Comment by kkapsner** [comment]
Thanks for your input.

The "violation" of RFC 4291 is on purpose because I do not want to talk to anything. I just need the browser to do something until the user made settings are loaded.
If you installed the version of CB that uses that technique you are using a WebExtension. Firefox ESR does support it - otherwise you are not able to install a 0.4.* version of CB.
The third point is definitely a proxy/OS bug as they should know that it's "the unspecified address" and should act accordingly (i.e. ignore it).

If you want to get rid of these requests you can use the *.*.*a versions of the addon. This versions simply block the canvas API until the settings are loaded. But this may break some websites.

PS: It's not possible to do a proper version check in a WebExtension at the point where it would be necessary.

**Comment by pacocc** [comment]
Thanks for the detail kkapsner.  Hope you're able to submit a bug report upstream to Mozilla and/or a feature request for a, what, api call?

**Comment by kkapsner** [comment]
There is already an API that will be present in FF 59. Already functional in CB.

**Comment by spodermenpls** [comment]
@kkapsner Now with FF 59 released, will you be able to merge versions a+b and include the new commits?

**Comment by kkapsner** [comment]
The current version already benefits from the new API in FF 59. But as long as FF 52 is still in ESR I want to support it. So a+b will remain till August...
But it's only a inconvenience for me on releasing a new version (which will happen soon hopefully).
