### ISSUE TITLE
Subsequent webpages not loading after visiting main page

### ISSUE THREAD

**Issue by Joel889** [kkapsner/CanvasBlocker#185]
Initial website is loading, but subsequent webpage is not. 

## Steps to Reproduce (for bugs)

1. Go to raise.com
2. Click on "Login" -- this page will not show the login form

3. Close tab and delete all cookies

4. Go to raise.com/user/sign_in -- this time the page is showing the form.
5. Click on the upper left logo to go back to the main page
6. Click on "Login" -- the page is once again not showing the form.

7. Close tab and delete all cookies, add domain to whitelist.
8. Repeat step 1 and 2 and everything is working.

## Your Environment

* CanvasBlocker Version used: 0.4.4b
* Firefox version incl. 32- or 64-bit: 64bit
* Operating System and version (desktop or mobile): Windows 7
* Installed addons:

**Comment by kkapsner** [comment]
This problem is caused by a tracking/fingerprinting script that uses the image https://rro.raise.com/beacon/pg/sdid.png and sets a cookie "sdid".
The page reloads if you just delete this cookie.

It seems that cloudflare rejects the HTTP-request if this cookie contains faked data. (I do not know if this is a cloudflare or raise.com thing.)

There is nothing I can do on the addon side to prevent this from happening. I have two suggestions: either you allow the tracking and set the minimal fake size to 20 (the tracking image has a size of 17x1) or you install something like µBlock origin and block the access to the image mentioned above.

**Comment by Joel889** [comment]
> It seems that cloudflare rejects the HTTP-request if this cookie contains faked data.

How does it know that the data is faked? Wouldn't this be a bigger problem in the sense that it could aid in identifying users, who are trying not be tracked?

**Comment by kkapsner** [comment]
The data they get in the cookie just does not match the expected value. Since this is for tracking and not for fingerprinting they know for sure what to expect in the cookie.

I am aware of the possibility that the presence of CB can be detected (see http://kkapsner.github.io/CanvasBlocker/test/detectionTest.html for the tests I am running). I just do not know a good solution for that problem yet.
