### ISSUE TITLE
Update translation

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#191]
Some italian translations are missing. This is what my test run returned:
```
missing italian for options
missing italian for optionsIntroduction
missing italian for installNotice
missing italian for updateNotice
missing italian for section_asking
missing italian for section_faking
missing italian for section_notifications
missing italian for section_lists
missing italian for section_misc
missing italian for section_settings
missing italian for showCanvasWhileAsking_title
missing italian for showCanvasWhileAsking_description
missing italian for showCanvasWhileAsking_message
missing italian for apiWhiteList_title
missing italian for apiWhiteList_description
missing italian for showOptions
```

@anthologist can you please do the translations?

**Comment by kkapsner** [comment]
All translations are missing some bits - I think this issue will never be closed... any translator can use the checkMissingTransaltion.js and translate.js tools that might help to get things done.

**Comment by Thorin-Oakenpants** [comment]
rather than open a new issue, I'll just drop this here: The description for CB reads (emphasis mine)
- A Firefox **Plugin** to protect from being fingerprinted 

I would change that to `extension`. A plugin has always referred to items like Flash, it even has it's own tab in about:addons. Mozilla, around the quantum release, changed their terminology (they even had a blog post about it) where they said they will refer to add-ons and extensions as `Extensions` (for web ext) and `Legacy Extensions` (for the non web ext ones), and start dropping the term add-ons. Almost everywhere they could, they have changed the UI to refer to `extensions`. They even renamed system add-ons as "Firefox Features" (as seen in about:support).

It's not perfect, because `about:addons` is the legacy URL. And the hamburger menu item still uses `Add-ons` -> Ctrl-Shift-`A`. But everywhere else, they use `Extensions` - this is what I would use in your description

PS: sorry if this sounds pedantic :kiss:

**Comment by kkapsner** [comment]
Where do you see the "plugin"? The current description should be "Alters some JS APIs to prevent fingerprinting."

Did you cache the extension descriptions and so you see the old one?

**Comment by Thorin-Oakenpants** [comment]
Go [here](https://github.com/kkapsner/CanvasBlocker) and look near the top

**Comment by spodermenpls** [comment]
@kkapsner The "Plugin" is in the repo description here on Github. 😏

**Comment by kkapsner** [comment]
Ah... thanks. I have changed it.

**Comment by KrasnayaPloshchad** [comment]
One possible solution is to integrate an online translating service such as Crowdin, Weblate or Transifex, then you’ll help users to know which of items is need to translate.

**Comment by kkapsner** [comment]
Good suggestion. Will have to check out how they work en detail.

**Comment by kkapsner** [comment]
Crowdin looks fine Let's try it: https://crowdin.com/project/canvasblocker (and let's see if I get an open-source licence for CB - otherwise we only have 14 days...)
