### ISSUE TITLE
Yellow notification in the new firfox not show

### ISSUE THREAD

**Issue by iwkb** [kkapsner/CanvasBlocker#198]
Dear Sir
In the old Firefox last stable version (53) if  a website is not good, a fake readout shows on the top of the screen for in my case 30 seconds with notification display time (yellow band).

In the new version of Firefox (60>) I see nothing anymore . In the options I do the same (but has more options)  The timer **notification display time *** is also gone.

Why is the yellow band important? It shows the website they  want to now more from you. You can show to other people that a browser is not always safe to use. Finally you know the add-on works!!

But it is possible that I do something wrong
Regards Lambertus Verhage
Netherlands

**Comment by kkapsner** [comment]
Dear Lambertus Verhage

usually people that file an issue are not that formal in their writing. And you do not have to be it either - but I do not mind it.

The yellow band (the notification) is no longer available for WebExtensions, which are the only addon type allowed from third parties (as I am) any more in Firefox. I created a new notification mechanism by using the page action button. This is a little fingerprinting icon that appears in the address bar (you can get further informations by clicking on it):
![pageaction](https://user-images.githubusercontent.com/1105157/41259964-ce7c12ca-6dd5-11e8-8ce1-44be5533248b.png)

Since this is far less obtrusive than the big yellow bar it does not go away after a certain time and therefore the display time setting is gone.

So the functionally is still there but displayed different.

Regards kkapsner
Germany
