### ISSUE TITLE
Feature request: Screen size spoofing

### ISSUE THREAD

**Issue by NewGen66** [kkapsner/CanvasBlocker#220]
Thanks for such a nice addon.

Please check if screen size spoofing can be migrated from RAS.

It should able to lock maximized window to spoofed resolution.

perfect app to see it live is "multiloginapp" you can create a firefox profile after signup and see how they spoof many things.

You can even release a separate addon like RAS

Thanks for your work.

**Comment by spodermenpls** [comment]
I'm not a fan of spoofing such things as User Agent, Screen Size or Time Zone, because it is (to my knowledge) circumventable and is more likely to make you more unique than less. I guess @Thorin-Oakenpants has the most knowledge on this topic, that he/she would like to share?

@NewGen66 I found this test page (http://dev.jeffersonscher.com/resolution.html), that is supposed to be able to read out the true screen resolution, can you share the results that come out while using RAS' screen size spoofing? Since RAS isn't available as a WebExtension I can't test it myself, as I use FF 61.

**Comment by crgithubmoth** [comment]
In spite of the spoof detection arms race, once your screen size is unique to 1 in10000 , it is time to deny the easy pick. Thanks for the link. Now we need a way to detect a spoof detection...smh

**Comment by NewGen66** [comment]
JavaScript screen.width x screen.height = 1440 x 900
window.devicePixelRatio = 1 device pixels per CSS pixel
True screen.width x screen.height = 1440 x 900

JavaScript window.innerWidth x window.innerHeight = 1152 x 709
window.devicePixelRatio = 1 device pixels per CSS pixel
True window.innerWidth x window.innerHeight = 1152 x 709

**Comment by spodermenpls** [comment]
@NewGen66 And what is the original screen resolution?

**Comment by NewGen66** [comment]
@spodermenpls 
1152x864

**Comment by spodermenpls** [comment]
@NewGen66 Thanks. Maybe the test page isn't sophisticated enough to detect the real screen size, I'm still not convinced that the screen size spoofing is watertight.

**Comment by Thorin-Oakenpants** [comment]
privacy.resistFingerprinting (RFP) has already covered all of this. It doesn't actually *lie* about the browser's inner window (or viewport) measurements (which can be grabbed by css anyway - see https://demos.traudt.xyz/css/media/index.html), because this would screw up website layouts etc (Note that zoom and DPI affects this). What it does do is make all other measurements report the same (i.e screen res, available screen res). Available screen res would give away entropy on position of task bars (top/bottom, or left/right) and their height or width respectively.

I'm not sure now, but JS used to be able, I think so don't quote me on this, to get other measurements as well such as the actual browser measurements, and maybe even mouse coordinates (relative to screen?).

eg if your inner browser is a windowed 1600x900 (on your new shiny 2560x1440 monitor), and you report screen res, available screen res etc as the same - then clearly you are lying (unless you are in full screen mode I think), because otherwise your browser has no chrome. So you are already in a very tiny minority. But as long as that tiny minority report the same consistent values, then you are as "safe" (eg RFP currently uses 200x100 measurements on browser start). Until you open or resize any chrome that affects it, eg resizing the sidebar, toggling the menu bar (alt key), using the findbar, etc .. or resizing the actual browser.

Look, even your scrollbar width leaks info. i.e when a scrollbar is present, your inner browser minus viewport area = scrollbar width. This leaks your OS, and in Linux, it can vary widely. Linux is already a small group, nailing you down to eg Arch is even more entropy.

The RFP patch also masks orientation. And overall, it covers lots of methods of getting your res (not an expert, but it's not just covering some basic JS, there's other APIs that can leak damaging info). RFP is a more comprehensive solution - look, it even refuses to store (or use existing) site specific zoom settings. You can still zoom etc, but it will only remember it as a per tab setting. RFP also protects you went you launch Firefox, or open new windows (eg you cannot open maximized), warns you (or will when bugzillas resolved) when going maximized / full-screen, and right now they are working on  a) snapping the browser inner window, and thus the whole browser) back into combinations of 128x100 when resizing or b) snapping the viewport inside the browser window to measurements of 128x100. Yup, they are moving away from 200x100

As far as Canvas Defender doing this, it's not needed and I would call it feature creep. RFP/Tor Uplift already has this covered, and there are extensions that already do this (I have not tested them, but I would say off the top of my head that they are not as complete a solution as RFP).

You best solution against any of this, is to block JS by default, or at least all 3rd party JS, and build rules for uMatrix. However, FP scripts are so easy to drop in (eg reddit uses https://github.com/Valve/fingerprintjs2 I believe) and as first party. I will say though that some of these scripts are pretty basic IMO, and could do a lot more, even with just screen measurements - they could easily ramp up the entropy by grabbing viewport and thus scrollbars (its down to decimal points), by comparing screen vs window (and thus did you lie), etc.

There's no easy answer. I've followed discussions on sizes, spoofing techniques, the pros and cons of each one, for years on tortrac and elsewhere, and they *still* haven't got a perfect solution. And you expect an extension (one guys?, not referring to kkapsner here) to provide a better answer than what can be achieved at a lower level in Firefox code itself, by the best minds at Tor and Mozilla?

**Comment by Thorin-Oakenpants** [comment]
Unless you lock out the Fullscreen API, your res can be grabbed anyway. This is the API that lets youtube videos etc have a `[ ]` fullscreen button in their player nav etc. You can disable this with

```
user_pref("full-screen-api.enabled", false);
```

Flip the pref to true and go visit https://github.com/earthlng/testpages/blob/master/docs/fullscreen_leak.htm

**Comment by Thorin-Oakenpants** [comment]
There's a big difference between lowering entropy and raising it (by randomly and frequently changing the spoofed values). There are merits in both, but TBH, I subscribe to TBB's philosophy of lowering it.

As for being on FF54, that's not good (no security patches, outdated software, no longer supported). If it was 56 I could understand a hold-out due to some XUL extension loss of functionality - but even then, you could  be using ESR52.x (for now). At the end of the day, if you wan to use Firefox (and not some minor fork like Waterfox), you **will** have to adapt. What's more important, some workflow or legacy ext functionality, or having a secure browser? I know what I would do. Adapt!!

**Comment by NewGen66** [comment]
@kkapsner 

![5](https://user-images.githubusercontent.com/41809366/43577717-36888cfe-9612-11e8-87aa-d0c199a89650.png)

**Comment by kkapsner** [comment]
@NewGen66 Thanks for the donation.
@all Thanks for the discussion. I think Thorin has a good point.

**Comment by kkapsner** [comment]
@NewGen66 can you please check if the options that rFP offers cover the functionality of RAS.

**Comment by NewGen66** [comment]
@kkapsner 

to my knowledge RFP introduction starts where the RAS addon stops even installing. i think FF 56+
when i try to install RAS on latest version of firefox it says "corrupted add on"

**Comment by NewGen66** [comment]
Chameleon on other hand is able to spoof screen resolution on latest firefox.

**Comment by kkapsner** [comment]
Spoofing the screen resolution is definitely possible. This is not the point of this discussion. The point is that RFP is integrated in Firefox and has much more, better and more reliable ways to protect you.
If it covers the needs you should use it.

RFP also provides some sort of canvas-protection but breaks some web pages. On the other hand if you allow these pages to use the proper canvas API you leak your fingerprint there. This is why CB is useful in this case as well: if the page breaks you can allow the API and CB will protect your fingerprint.

I do not quite see a similar scenario with the screen size (limiting the screen size to multiples of 128x100 will not break any site). That's why I asked if RFP covers the needs or if there is an edge case that would need some further tweaking.

**Comment by NewGen66** [comment]
@kkapsner 

All in all i am looking for unique FF profiles, multiple.
RFP does not serve good for me. I do not want to blocking fingerprints, instead i want to have different profiles serve different screens and fingerprints (CB does it nicely)

**Comment by crssi** [comment]
@NewGen66 

> Chameleon on other hand is able to spoof screen resolution on latest firefox.

No its not. Thare are many ways how to get screen resolution even without JS, merely with CSS.
All kinds of using WE to spoof screen resolution, just leads to even more uniqueness and the same goes to agent,OS,bitness spoofing.
Best is just using RFP.

See POC: [https://demos.traudt.xyz/css/media/index.html](https://demos.traudt.xyz/css/media/index.html)

**Comment by Thorin-Oakenpants** [comment]
>  instead i want to have different profiles serve different screens and fingerprints

Then you are on a losing team IMO. Spoofing (which RFP only does for no inner windows) in general (eg user agents, whatever) only makes you more unique, because it it so easy to determine that you lied. very few people lie. It is better to be .. wait for it ... PALUSIBLE

**Comment by NewGen66** [comment]
You can close the issue, if you like to.

**Comment by Thorin-Oakenpants** [comment]
@NewGen66 RFP does sooooo much
- https://github.com/ghacksuserjs/ghacks-user.js/issues/7 - First post contains a carefully curated list with info for you, links to the bugzilla's etc. And at the very top are some links
- https://www.torproject.org/projects/torbrowser/design/index.html.en - get a pot of coffee, and read from start to finish. It's a bit dated in some sections, but the whole philosophy of *reducing* entropy in buried in there
- have fun :)

**Comment by NewGen66** [comment]
What i want to do is present unique and same fingerprint every time i start a specific firefox profile (screen size, user agent, etc)
I do not want to randomize them.

There are like 10 firefox profiles

**Comment by kkapsner** [comment]
OK - I see your use case now. I'm not sure if CB is the right place for something like that.

**Comment by NewGen66** [comment]
No problem @kkapsner thanks, CB is helpful at most of part.

**Comment by crgithubmoth** [comment]
I used resist fingerprinting, but got very rare screen sizes, that did not fool all test sites.
As Thorin noted above, this is 2 strikes against us.
For phone and tablet, we need an effective spoof that gives full HD size with appropriate rotation.
I will gladly use anything better than resist fingerprinting.
Thanks for your generous attention.

**Comment by privacyguy123** [comment]
So what we are saying here is: it's not possible to spoof screen size without having that godawful resistFingerPrinting option on?

**Comment by kkapsner** [comment]
Not quite. The screen size (e.g. the JS properties ```screen.width``` and ```screen.height```) can be spoofed like any other value (e.g. the ```navigator``` properties) BUT if you only change these you may create a completely unrealistic scenario over all (e.g. you screen size is much smaller than your browser window size which is very hard to fake as there are so many ways to obtain them and a lot of them are not controllable by a webExtension).

The RFP option is deeply integrated in the Browser and can do things that a WebExtension cannot do. I know that it has its drawbacks but for this type of thing I think it's the better way.

**Comment by Thorin-Oakenpants** [comment]
For whatever reason (and this was a long time ago), Tor Browser (and the subsequent Tor Uplift to RFP which was based on it), decided to tie all the metrics to a single point: the "inner window". And the idea was that every new window starts at one of a few inner window sizes depending on the screen resolution (capped at 1000px wide and 1000px wide), and they tell people not to resize.

PS: the inner window makes sense: i.e do not lie about it: because there are too many ways to measure it, and lying can cause weird side effects, breakage

Fingerprinting likes stability, and an inner window measurement is not stable (so many other factors which are not stable affect the inner window). Scripts in the wild do not bother with inner window measurements. That doesn't mean that we don't try to protect that, as it is still a threat, depending on the threat model.

In trying to solve one issue, they created another. I'll put it this way: we have **screen** and we have **chrome**. By tying screen metrics to a chrome one, they have made the number of screen metrics every single combination possible (as soon as you change the chrome you get new values, and those values can increment by 1 pixel). This is what letterboxing is trying to fix - by reducing the number of possible results. It's still quite a few possible combos.

Back to what I said earlier about scripts in the wild. So without letterboxing (and the new window sizing has issues = quite a bit of entropy there), **screen** measurements were, for arguments sake: 15 different results, assuming the user did not resize. But users resize, manually, they go full screen, they maximize, etc. Not only does this make them more unique, but it also raises the entropy of those who do follow the "rules" (don't resize etc): although to be fair, what really matters is increasing the number of Tor Users.

Now enter Letterboxing. This fixes a few quirks with new windows, so for arguments sake, lets say we're down from 15 different results to 5. Awesome. But now people may feel safer resizing. It's a usability thing.

Some number off the top of my head
- no RFP + no LB: the "screen" entropy is limited by the real world distribution of actual screen used: e.g you won't find one at weird sizes like `1953x1085`
- RFP + no LB: the number of results you can return is everything because the inner window can change in 1px steps
- RFP + LB: the number of results is much less (stepping in 50px for low res, then 100px in height but 200px in width = removes most combinations possible. Do the math.
   - example, on my screen (2560x1440), lets say I use at least 600pixels wide: I can get at least 10 different widths. Height, I have 1380 available due to my double height task bar, and lets say I keep over 600px. I can get eight different heights. So that's **eighty** (10 x 8) possible different screen sizes I can report
   - Not ideal, considering maybe the top 4 or 5 desktop screen resolutions cover 90% of people.

Oh, and I haven't mentioned how zoom affects this... the rabbit hole goes deep

---

**What they should do** is treat **screen** and **chrome** separate. This is for desktop. Android is a different kettle of fish that users don't resize, etc: totally different

All chrome metrics tie to the inner window and letterboxing stays

But screen metrics (which is what FP scripts actually try to get) could be spoofed from a much smaller limited set (they don't have to be common ones, but blending in and being plausible never hurts). The screen metric doesn't have to be static. It can step as well, based on the inner window. Just always report "at least" the current inner window from the values in our limited set.

If an extension can spoof screen after RFP (which you can, right?), then you could easily implement something like [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1591337#c2). What I'm not sure of is if your extension can get the inner window measure when letterboxing is enabled, and it needs to get it without zoom affected it (we can do that in FF code, I just don't know about extensions).

f.....k .. I wrote a novella

**Comment by Thorin-Oakenpants** [comment]
PS: you can't control @ css media via an extension, so yes, you would get busted as very unusual (but not for an enforced set of users like TB or RFP users if RFP implemented it). The css media one is kinda edge PoC: it takes a lot of server side resources IMO and there is way much lower hanging fruit.

The idea (stepping screen based on chrome) needs a little bit of tire kicking: but I've been thinking about it for years, and I think it's solid AF (for desktop)

**Comment by kkapsner** [comment]
Interesting novel you wrote there. I will give it a shot... and then you have to test it ;)

**Comment by Thorin-Oakenpants** [comment]
The tests are already built: TZP

**Comment by kkapsner** [comment]
Regarding the @ css media: I think I have really bad news. You don't need any server side resources to extract the screen size from them: https://canvasblocker.kkapsner.de/test/screenSizeTest.html

Since the device-... media queries exists and work (as stupid as they are - and they are deprecated for good reason) and I do not see a good/feasable way to fake the values in the css test I'm not sure if it's worth including it in CB. Having inconsistent values there would just make you more "fingerprintable".

@Thorin-Oakenpants what are your thought about my tests?

**Comment by kkapsner** [comment]
PS: shouldn't be Letterboxing be in the nightly version of FF? It does not seem to work for me. Or do have to enable it somehow (I did enable RFP).

**Comment by r-a-y** [comment]
The letterboxing option is privacy.resistFingerprinting.letterboxing

**Comment by Thorin-Oakenpants** [comment]
> Regarding ...

@ css media was a PoC (matt traudt, arthur edelstein) to show that your screen could leak without JS. I'll have to look at the match media (deprecated?) JS one to see if it's in my list. The good news is that RFP/LBing covers this.

As mentioned, what you can't cover with an extension, is likely to not be used in the wild. Scripts will propbably get more complex as FPing grows - I think I read a report a few months ago that of the top 10,000(?) sites it jumped from 1% to about 6% in a year: namely those 3rd party ad networks. But they have so much low hanging fruit, that they don't bother. Seriously, they are all drop in copies of the same sh^t :)

Obviously any "leak" of a spoofed value is not ideal - as it creates an "information paradox" which can cause usability / breakage issues. Not to mention that you also leaked the real value. And the combined values = more entropy.

With this approach, if you step to e.g. four common widescreen desktop monitor sizes to cover the range: it does two things: one: it's variable (FPing hates instability) if the user resizes which may help (I have no real idea how people use their browser), and two: if users are generally maximized, or use most of their screen, they will probably not be lying but actually be in one of the common screen resolutions

I'd have to look it up, ~~but lets just say that 4 screen resolutions account for 75% of users: the set in the bugzilla is three sizes plus 4k~~

https://data.firefox.com/dashboard/hardware
- `1366x768` = 30%
- `1920x1080` = 31%
- `1600x900` = 8%  (not in the list on bugzilla)
- `2560x1440` = 1.5% (I think, hard to read)
- `4K` - no-one? but  needed as an upper bound

The other thing is that Firefox can do things in code you can't. So screen orientation could be a factor (which RFP tries to cover but they have a few holes: just not high priority). But this is for desktop, and I don't think there is much we can do (for now) about portrait monitors.

---

PS: your tests (and extension) need to cover `available` screen res

**Comment by Thorin-Oakenpants** [comment]
sorry it's WaPo .. I assume you have 3rd party disabled, or even JS (it works fine, no idea how much shit they throw at you): https://www.washingtonpost.com/technology/2019/10/31/think-youre-anonymous-online-third-popular-websites-are-fingerprinting-you/

> At least a third of the 500 sites Americans visit most often use hidden code to run an identity check on your computer or phone

in other words, fingerprinting: and it's driven by the ad networks. Tell me something I don't know

**Comment by insertf4** [comment]
hi
Virtualbox with guest linux has flexible window size and as result resize window on some pixels you are detected by unique size ex 1584x849. as wrote below ex ... 1600x900 (on your new shiny 2560x1440 monitor ... and global problem with 4k monitor users.
As option to spoof this, as recommended **Thorin-Oakenpants**
 set user_pref("full-screen-api.enabled", false); and before serf set browser tab in Responsive Deging Mode and set require window size. After check on https://canvasblocker.kkapsner.de/test/screenSizeTest.html
without Responsive Mode, but with full screen false in about;;config window size was detected as flexble and real ex 1723x954, after refresh test with Resposive Mode window size was spoofed succefull and reflect as usual user 1440x900

**Comment by kkapsner** [comment]
First draft on alpha is out. Please test.

**Comment by Thorin-Oakenpants** [comment]
I did a quick test. Some quick thoughts / observations

- Isn't 4K `3840 x 2160` ? you use `4096 x 2160`
- without looking at your code, is there a step up after 4K?
- why jump from `1920 x 1080` to 4K ...why not use `2560x1440` and then 4K

I also turned off everything except screen, and it eats a fair bit of CPU: I was constantly resizing: I guess browsers are pretty static and not always in a resize state : I assume this is the matchMedia code beavering hard away in the background

Observation: with RFP enabled (ignore letterboxing which doesn't really matter in these tests), it's interesting to see how the matchMedia test fairs (from memory it was spoofed with RFP off, but not when RFP was on: RFP kicked in after and returns the inner window).

I will have to do a proper full on test with RFP on and off, and all pure css @ media rules, to see what is and isn't affected.

PS: I only used my wee test page at https://thorin-oakenpants.github.io/testing/ for some quick tests.

**Comment by kkapsner** [comment]
>Isn't 4K 3840 x 2160 ? you use 4096 x 2160

It depends on the ratio 19:10 is 4096 and 16:9 is 3840. I used the bigger one to cover more.

>without looking at your code, is there a step up after 4K?

Yes there is 8K above 4K (8192x4320) - but I might switch to 8192x6144.

>why jump from 1920 x 1080 to 4K ...why not use 2560x1440 and then 4K

It seems I deleted 2560x1440 at some time... don't know why. Will reintroduce it.

>it eats a fair bit of CPU

I also noticed that the mediaQuery code is hard on the CPU. But I don't think that performance is that important here...

**Comment by kkapsner** [comment]
My test page is also heavy on CPU when the screen protection is deactivated...

**Comment by kkapsner** [comment]
For all the people not yet using the alpha: please check https://canvasblocker.kkapsner.de/versions/

**Comment by spodermenpls** [comment]
I am testing right now, and it seems to work fine. The only difference (between Screen API protected/not protected) in the Screen size test are the "window properties: outer..." being now the same as "window properties: inner...", the other values are always one and the same.

**Comment by kkapsner** [comment]
So you do not have a taskbar? Otherwise the avail... properties should also be the same as the screen size.
And nothing changed when you resized the browser window to very small?

**Comment by spodermenpls** [comment]
OK, I may have misread, "screen properties: avail..." shows 40 pixels less in height, when the protection is off, and 1600x900 when enabled. I guess that's the taskbar height?

**Comment by kkapsner** [comment]
Should be.

**Comment by spodermenpls** [comment]
What about smaller screen sizes on Android devices? I've tested it, but the spoofed values aren't consistent (expectable, since only desktop screen sizes are in place so far). The new Screen API protection is activated by default, so either it should be deactivated for mobile devices, or those smaller screens should be supported as well. CB has round about 5,000 Android users right now, so this affects more than just me...

**Comment by kkapsner** [comment]
Good point. Actually I thought about setting "fakeMinimalScreenSize" to false by default. Not sure if I want different default settings for mobile and desktop.

If we include mobile screen sizes which ones should we use?

**Comment by spodermenpls** [comment]
That's the question, mobile devices come (and are about to come) in a lot wider variety of screen resolutions than desktop screens, so trying to collect and maintain every single display ratio/resolution out there might be unreasonable. Why can't the checkbox "fake minimal screen size" be unticked for CBs running on Fennec? You said you prefer not to have different defaults for mobile and desktop, would that small of a difference be that much of a hassle?

**Comment by Thorin-Oakenpants** [comment]
> so trying to collect and maintain every single display ratio/resolution out there might be unreasonable

It doesn't matter what you spoof as, as long as the set is limited: and everyone is the same set. Being plausible is always a good idea: there's no need to monitor and keep a database of measurements. But for android, you'll just look silly - see the next bit

---

the whole proposal to reduce entropy in screen (aimed at Tor Uplift, which ties screen to inner window) doesn't fit the same threat model for Firefox users (unless they have RFP on).

However, as already stated, and also in the bugzilla

https://github.com/kkapsner/CanvasBlocker/issues/220#issuecomment-547734811 [and by resize I meant resize the browser, not pinch-to-zoom]
> This is for desktop. Android is a different kettle of fish that users don't resize, etc: totally different

https://github.com/kkapsner/CanvasBlocker/issues/220#issuecomment-549102173
> But this is for desktop

OP's description at [1591337](https://bugzilla.mozilla.org/show_bug.cgi?id=1591337)
> This is for desktop

Android is already using as much screen res as it can (IDK about tablets running android: chromebooks?). Anyway the idea was to exclude android because it's so problematic.

**Comment by kkapsner** [comment]
Actually I'm not sure how big the hassle is...

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.15-RC1

**Comment by kkapsner** [comment]
Version 1.0 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0

**Comment by asakura42** [comment]
@kkapsner `window properties: inner...` on test page still shows size based on real size of the page in window

**Comment by kkapsner** [comment]
Yes, the inner... values are not changes. Two main reasons for that:

1. it may break the layout of web pages badly
2. there are other ways to get them which I cannot fake -> potential of detection

It should not be dangerous information but to be on the save side you should browse with an inner window size that matches a common screen resolution or the default size of the Tor browser.
On the other hand - if you resize your browser window regularly your fingerprint changes everytime...

**Comment by spodermenpls** [comment]
@kkapsner I have a new Framework Laptop 16 here, with 2560x1600 pixels (16:10).. I ran the screen size test, the results worry me a little bit however (this is with standard "100 %" zoom): 
![Screenshot 2024-03-31 at 03-24-54 Screen size test](https://github.com/kkapsner/CanvasBlocker/assets/23747593/fb1cff40-e277-44f4-8daa-1341cdead59a)
Is this consistent enough, or does the 16:10 ratio and/or the ~2.5k resolution of the screen create too much entropy with the current CB setup?

**Comment by kkapsner** [comment]
> I have a new Framework Laptop 16

nice

> 2560x1600 pixels

Do you have a scaling in windows active?

**Comment by spodermenpls** [comment]
> > I have a new Framework Laptop 16
> 
> nice

Indeed it is.
> 
> > 2560x1600 pixels
> 
> Do you have a scaling in windows active?

Yes, that seems to be the culprit.. standard setting is 150 %, when I set it to 100 %, all the consistency tests are flawless, just that everything is being displayed way too tiny. What's your recommendation in this high-DPI case?

**Comment by spodermenpls** [comment]
@kkapsner Should I leave it as it is (in case it's not too grave of a concern regarding detectability), should I deactivate "fake minimal screen size" and set a manual screen size instead, or is there something to be done on the CanvasBlocker side? Only thing clear is that "150 % scaling" needs to stay, for the screen to be usable.

**Comment by kkapsner** [comment]
I think have 150% scaling is nothing special and a lot of people are using it. So I would leave it...

**Comment by spodermenpls** [comment]
@kkapsner Alright, that makes sense.
