### ISSUE TITLE
Content Security Policy warnings in all sites if the extension is enabled

### ISSUE THREAD

**Issue by Saoshyant** [kkapsner/CanvasBlocker#224]
Specifically:
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: Couldn’t parse invalid host *report-to

End quote.

Those disappear if I disable the extension and reload the pages.  Probably easy to fix: just place correct values in wherever the extension is sending those HTTP headers.

**Comment by kkapsner** [comment]
This is intentional as Firefox ESR wants it the other way around. It says that 'frame-src' should not be used and 'child-src' instead and it does not know 'worker-src'. To have support for ESR and the current Firefox I added both headers: https://github.com/kkapsner/CanvasBlocker/blob/master/lib/dataUrls.js#L52

The report-to is there because of https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#Reporting_directives

BUT there is a slight typo which I have to fix. I will remove the "invalid host" message but add an "unknown directive" message...
