### ISSUE TITLE
[alert indicator] Use color and/or animation to increase visibility

### ISSUE THREAD

**Issue by h3298** [kkapsner/CanvasBlocker#225]
Suggest using red color (and blinking if possible) to improve indicator visibility

![fingerprint](https://user-images.githubusercontent.com/20834957/43610754-07739220-9675-11e8-9938-484a0d8dd311.png)

**Comment by kkapsner** [comment]
Hm... I quite like the clean look of the icon... but I also see your point... let's see what I can do.

**Comment by Thorin-Oakenpants** [comment]
just my 2 micro-bitcoins (or cents)

I like that the urlbar icon does not show if not used. It's mere presence indicates that canvas is attempted (it may or may not actual do anything depending on `privacy.resistFingerprinting`). Staying a nice neutral color is best IMO. And this also allows pulling out detailed info

We have a toolbar icon now, that changes color. Green = nothing to see, move along people. Red = canvas is being called, or it was, now I assume it could mean canvas, audio or both

My only question would be, could the toolbar icon indicators be improved. Personally I would prefer a badge, rather than an icon color change. I'm not sure what triggers the color change, but if it includes audio, then IDK, maybe something like a badge `[C]` for canvas, `[A]` for audio, and `[2]` for both

**Comment by kkapsner** [comment]
I will make this some settings.

**Comment by kkapsner** [comment]
@Thorin-Oakenpants: can you please create a new issue for the badge?

**Comment by kkapsner** [comment]
Please check https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha2

**Comment by spodermenpls** [comment]
@kkapsner The new badges look fantastic! I've noticed so far only one minor "issue" (http://www.bilder-upload.eu/upload/4e4eea-1535409086.jpg); is it possible to insert a gap between "CanvasBlocker" and "Schutz/Protection", so they're not attached together when displayed in the tool collection menu?

**Comment by kkapsner** [comment]
I will add a space there.
