### ISSUE TITLE
[BUG] Google picture captchas fail to render on ouo.io

### ISSUE THREAD

**Issue by DonJuan777** [kkapsner/CanvasBlocker#23]
When I visit a site like this ouo.io .. Google is using new picture captchas instead of letters and it calls out faked readout for Canvas but the pictures to solve the captcha never show up unless I whitelist  www.google.com . The addon is not working for this is there anyway to fix it

**Comment by kkapsner** [comment]
I do not see any captcha on ouo.io ... where is it?

PS: reCAPTCHA is working fine for me at http://www.google.com/recaptcha/demo/

**Comment by DonJuan777** [comment]
Here is and example link 
http://ouo.io/7xkHU

Here is a screenshot of it using fake read out you cant see pictures 
http://i.imgur.com/Jdra7Tk.png
This what it should look like only works when whitelisted
http://i.imgur.com/OVVPlBd.png

**Comment by DonJuan777** [comment]
Also I run another test with your addon set to allow everything  and set RAS to block Canvas instead I ran a test at https://panopticlick.eff.org/  and https://www.browserleaks.com/canvas and it passed both test .It only has Canvas (basic support). and i can see the Goggle picture captchas  blocking Canvas with RAS  its just using you addon its not working .

**Comment by kkapsner** [comment]
OK - I see your problem now.

Since reCAPTCHA does not have a fallback for browsers without canvas support there is currently no other way than whitelisting it. But you do not have to whitelist complete google.com. You can also only allow the reCAPTCHA path by adding ```^https?://(www\.)?google.com/recaptcha/``` to your white list. This will only allow URLs that match this particular regular expression.

Maybe I will add a even finer way of controlling the access to canvas-APIs in the future. But for the moment I'm sorry this is a "wontfix".

PS: The tests of browserleaks will display a different fingerprint signature everytime you refresh. This means you can not be identified when you're using the "fake readout" though you are reported to support canvas.
