### ISSUE TITLE
Indicate whitelisting on toolbar icon (or badge)

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#241]
If a page is whitelisted it should be indicated on the toolbar icon or the badge.

Spec:
- only the top level URL (what's in the address bar) will be checked
- following settings will be checked:
    - block mode (indicator when is set to "allow")
    - whitelist
    - temporary whitelist

Ideas:
- different badge color (preferred)
- different icon color (would collide with the notification highlighting)
- special badge text

@Thorin-Oakenpants: what are your thoughts?

**Comment by Thorin-Oakenpants** [comment]
Just some thoughts (generally with extensions I've used)
- I am not a UIX expert
- not a fan of changing badge colors, the badge itself indicates something has been done - using this to indicate it is not doing something seems diametrically opposite
- changing badge colors could be used to indicate different types of action, but only complicates matters
- having multiple colors can get in the way of themes and/or be confusing
- a lack of a badge means nothing needed doing (eg see HTTPS-Everywhere)
- an icon color to greyscale indicates *full* whitelisting (eg uBo, uM)
  * with Stylish it becomes a dimmer icon rather than a bright one

Obviously any configuration/UIX can be used, depending on the complexity of what you're trying to achieve, but the question really comes down to what is "industry" standard (or how users would expect it to work).

I haven't even updated CB to the badges version yet. So assuming badges are not optional I would have the icon in two colors
- original red = active for current top level domain
- greyscale = whitelisted for current top level domain (included about: pages etc)
- badges in one color

> would collide with the notification highlighting

I'm not sure I follow this. The badge is the notification indicator

**Comment by kkapsner** [comment]
> So assuming badges are not optional 
You can deactivate the badge if you want to.

> I'm not sure I follow this. The badge is the notification indicator
You can also have a color change on the toolbar icon as a notification indicator

**Comment by kkapsner** [comment]
I will go with the gray icon for whitelisting: 
![grafik](https://user-images.githubusercontent.com/1105157/45172255-1fa09b80-b205-11e8-840e-895dcf181b59.png)

Should the toolip text also reflect the whitelisting?

**Comment by kkapsner** [comment]
The question is: what happens if the url of a tab is whitelisted but an iframe within is not? And the other way round?
Should the icon stay gray? Or should it be red?

**Comment by kkapsner** [comment]
Not sure if this only just a little bit confusing or a lot:
![grafik](https://user-images.githubusercontent.com/1105157/45246137-f44ea700-b2ff-11e8-8a7e-99d9aaf337d1.png)

**Comment by spodermenpls** [comment]
Is a whitelist badge even useful, with all the external resources that are embedded in modern websites? This message would confuse the shit out of me, if I didn't think about for 5 minutes before posting this..

**Comment by kkapsner** [comment]
Most of the external resources are not included via iFrames/frames and will therefore not create this kind of message (they are also whitelisted as I check the URL of the tab and not the URL of the executed script).

**Comment by kkapsner** [comment]
I think I will go with that in the first place and see how many confused user arrive. In the notification popup the user can have more information about which URL/domain was protected.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-RC1

**Comment by kkapsner** [comment]
0.5.4 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4
