### ISSUE TITLE
How best to configure CB to pass all detections on the Detection Test page?

### ISSUE THREAD

**Issue by sanjayen** [kkapsner/CanvasBlocker#249]
This is not a bug but to understand how to make CanvasBlocker the default handler for the multiple protection it offers.

@kkapsner thank you for a wonderful addon. I have been using CB for a long time using the default settings. With the Audio and History blocking, CB has become more useful.

I use various ghacks-user.js tweaks, hardening addons as well as a lot of other addons for specific needs.

With the current config, I am only failing the following tests. Every other page works perfectly.

Detection test [https://canvasblocker.kkapsner.de/test/detectionTest.html]
function code: CB detected
window name change: CB detected
error properties: CB detected
known pixel value test 1: CB detected
known pixel value test 10: CB detected

DOMRect Fingerprint test [https://canvasblocker.kkapsner.de/test/domRectTest.html]
CB does not block anything as the CB icon does not change color from the initial green.

Disabling the history.length and Window.name User Scripts [from https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts] takes care of function code and window name change detection.

Similarly, if I disable privacy.resistFingerprinting from about:config, the known pixel value test 1 detection is prevented.

I disabled all extensions and tested the page but the remaining 2 detection do not go away viz. error properties and known pixel value test 10. Please note - I have not tried with a fresh profile, which will probably not have this problem.

Here are my questions;
1. How do I debug to find out what setting/ addon is preventing CB from blocking these detections?
2. With CB installed, should I default RFP to false as otherwise known pixel value test 1 does not get blocked.
3. Lastly, how do I debug what is failing in the DOMRect test?

Thank you again for a great addon. Keep up the good work.

## Your Environment
* CanvasBlocker Version used: 0.5.3
* Firefox version incl. 32- or 64-bit: 62.0 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Home 1803 64-bit
* Installed addons: Anti-Paywall, Auto Tab Discard, Bloody Vikings!, CanvasBlocker, Chameleon, ClearURLs, Cookie AutoDelete, CSS Exfil Protection, Decentraleyes, Detect Cloudflare+, Disconnect, disqus-undirect, Don't touch my tabs!, DuckDuckGo Privacy Essentials, ETag Stoppa, Facebook Container, First Party Isolation, Google Container, Header Editor, HTTPS Everywhere, Nano Defender, Neat URL, Print Edit WE, Privacy Enhanced Mode for Embedded YouTube, Privacy Possum, Redirect AMP to HTML, Skip Redirect, Smart Referer, Stylus, SuperStop, Tab Session Manager, Temporary Containers, Trans Europa Express, uBlock Origin, Universal Bypass, Video Speed Controller, Violentmonkey

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {
		"displayAdvancedSettings": false,
		"displayDescriptions": false,
		"blockMode": false
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 100000,
	"rng": "persistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 1,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1536379592200,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "22",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}

**Comment by kkapsner** [comment]
Question 1 is tricky. With all the default settings only the "known 10 pixel" test will fail. There is the "fake input" mode which helps here, but as all the other APIs are only read APIs they will not be protected with this mode... (maybe I should change that)
And I know of a way to detect even in the "fake input" mode. (Hint: use the webGL-test)
You can also set the "minimal fake size" to something bigger than 10 and that test would be passed, but then a "known 100 pixel" test would fail. It's kind of built in as CB changes the content of a canvas. If you know what you are supposed to see you will detect the difference.

All the other tests are kind of validation tests for me and need some deeper digging if they fail. For your "error properties" you should hover your mouse over the red text and some technical information will show up. Hopefully we can debug this here. It could come from one of the other addons.

Question 2 is a good one and my answer is: it depends...;)
If you are fine with Firefox nagging for canvas permission and some pages breaking because of the completely white canvas it sees (check the "Fingerprinting test" with RFP enabled) it's a great choice as it's a first barrier which is also used in the Tor browser. If you then have a page that needs canvas permission to work CB jumps in to protect you from being fingerprinted.
Also RFP has some other effects you need to be OK with besides canvas protection.

Question 3 will answer itself: DOMRect is not protected in 0.5.3 as it's a new feature in 0.5.4 (see #236)

**Comment by sanjayen** [comment]
Question 1 - I will need to learn more about canvas and how it works, as I can today only nod in agreement but not understand completely what you are saying or hinting at :)

I did not know that there was a mouseover. Here is what error properties displays;

Error stack starts wrong. Expected: @https://canvasblocker.kkapsner.de/test/detectionTest.js - got : applyWithUnproxiedThis@https://canvasblocker.kkapsner.de/test/detectionTest.html:516:12

Similarly, here's what known pixel value test 10 displays;

wrong value 254 at 0 expected 255

Question 2 - Got it. This probably needs more testing on my part (disabling RFP) and using other configs or addons to get the same amount of protection along with CB. I am inclined to trust CB more than a single about:config, which cannot be manipulated with a whitelist.

Any idea if someone has achieved RFP using CB and other addons/ configs?

Question 3 - will wait for 0.5.4 to test this.

Any reason why Firefox keeps prompting a slow script warning for CB when browsing https://www.bromite.org/detect with CB 0.5.3?

**Comment by kkapsner** [comment]
> got : applyWithUnproxiedThis

I am sure this problem comes from a different addon. You can disable CB and the "error" detection test will still fail.

> Any idea if someone has achieved RFP using CB and other addons/ configs?

I don't know. But some people are quite happy with RFP. It's up to you and your use cases.

> Any reason why Firefox keeps prompting a slow script warning for CB when browsing https://www.bromite.org/detect with CB 0.5.3?

The reason is the audio cache and a very badly written audio fingerprinting script.
