### ISSUE TITLE
Can CanvasBlocker trigger anti-fraud systems on financial sites?

### ISSUE THREAD

**Issue by anonsubmitter** [kkapsner/CanvasBlocker#262]
Is it possible that CanvasBlocker could trigger anti-fraud systems on banking sites, payment processors and the checkout pages of ecommerce sites?

TL;DR: Should I turn off CanvasBlocker when doing financial transactions online or will nothing happen?

**Comment by kkapsner** [comment]
I never encountered problem with it with anything like this. But you should contact your bank if you have doubts. They should be able to tell you.

**Comment by spodermenpls** [comment]
I'm using CanvasBlocker, uBlock Origin and uMatrix simultaneously all the time, and while using 5 different bank websites and a handful of transaction providers like PayPal or Alipay, I've never encountered any problems or accounts being locked (and don't worry about eCommerce sites, most of them aren't that sophisticated anyway and struggle with any kind of protection against intruders and fraudsters..).
I doubt that contacting ones bank will provide much benefit, since they'll most likely just tell you to switch off any (theoretically hazardous) third-party add-on when using their sites.. @kkapsner And you and your coding are trustworthy, right? 🤔

**Comment by kkapsner** [comment]
> But you and your coding are trustworthy, right?

... guess so...
