### ISSUE TITLE
Unable to delete a whitelisted entry in Protect DOMRect API section

### ISSUE THREAD

**Issue by Rtizer-9** [kkapsner/CanvasBlocker#291]
I was facing an error in imdb site (I recall facing same error with the domrect faking feature of Scriptsafe addon) so I first thought of whitelisting it but for once I wanted to enable it again and found that the black cross icon just don't delete the entry. 

We only have option of checking and unchecking the checkmark which is a bit confusing to me. 

What purpose does the checkmark serve when the cross button serves the purpose? (Is it for saving us from again n again entering the domains and make the process of enabling and disabling the faking on a problematic domain more convenient by just entering once and using checkmarks for problematic instances?)

Also 

1. Please help me understand the relation between resistfingerprinting and portal.pushbullet.com QR code problem.

2. I don't recall the last time I got notif from Firefox asking me about that html canvas data. I haven't made any changes in the CB so I'm concerned whether everything is going alright under the hood. (What's the recommended method of testing your configuration when you've enabled resistfingerprinting?)

Thanks :)

**Comment by kkapsner** [comment]
Please read https://github.com/kkapsner/CanvasBlocker/issues/245#issuecomment-419186133 for further insight on how the checkboxes and the cross work. If you have suggestions on how to improve the UI please tell me.

Your problem with not being able to remove the whitelisting is due to the fact that the button in the popup sets the value for the block mode and not for the specific API. You see the URL entry on the other url specific settings as well for convenience reasons. They disappear when you remove (clicking the cross) all URL specific values for that URL.

For the other two questions:
1. RFP modifies the canvas API in that way that only a white image can be extracted (e.g. you will see do image on https://canvasblocker.kkapsner.de/test/test.html when it's enabled). Therefore no image information can be processes. You have to allow the usage of canvas on that domain. CanvasBlocker will still protect agains the fingerprinting in that case. 
2. I think they removed the notifications for RFP - I do not know when and why. It should still work under the hood. You can allow canvas in the page info page: 
![image](https://user-images.githubusercontent.com/1105157/47719829-9ded4d00-dc4c-11e8-9209-f29d25a5569e.png)

@atomGit I do not quite get your problem. Please open a separate issue with a detailed scenario and all your settings.
