### ISSUE TITLE
[Question] History Sniffing

### ISSUE THREAD

**Issue by Kraxys** [kkapsner/CanvasBlocker#295]
Does CB's History Protection feacture protect against [these](https://www.spinda.net/papers/smith-2018-revisited.pdf) new history sniffing methods ?

**Comment by kkapsner** [comment]
No, it does not. But I might have some ideas to break the timing attacks.

**Comment by kkapsner** [comment]
We could tweak `window.performance` to randomize the output a little bit. But as the general idea is not about the exact timing numbers but on the order of magnitude we also would have to tweak `Date` to get a consistent picture. Since I definitely do not want to do the later this enhancement will not be done. I'm sorry.
