### ISSUE TITLE
mega.nz login button not working

### ISSUE THREAD

**Issue by SeriousHoax** [kkapsner/CanvasBlocker#306]
Login button on https://mega.nz/ not working with default settings

It was working fine few days ago

Firefox 65 Beta
Canvas Blocker: 0.5.6
OS: Manjaro Linux

**Comment by SeriousHoax** [comment]
> I release 0.5.6 yesterday. So it might be an issue with that.
> 
> But I cannot reproduce your problem. It's working for me (on Firefox 64, 65 and 66)
> 
> Do you see any related messages in the Browser console (Ctrl+Shift+K)?
> Did you test on a fresh profile?

This is what I get on the console. Something is wrong probably.

https://drive.google.com/open?id=1aWs5G3PP1SyTrpxuftEx43TAmXER8wo4

**Comment by SeriousHoax** [comment]
Well I figured out what was causing this problem. I was using another extension for some additional tracking features. Either disabling that particular protection or canvas blocker fix the problem. So, I disable this option from that extension.

[img]https://mnmlsv.net/images/7023ed526005fe455f61a18c9a279dbc.png[/img]

**Comment by kkapsner** [comment]
This feature was not changed by the last release. But I think it's to a new loading order now - before it could have been CB then other addon and now the other way around.

You could try to disable and reenabling the other addon and see if the issue is gone.

But having both addons protect getClientRects is not ideal. I do not know how and which other features of the DOMRect are protected by the other addon. CB tries to cover all of it.

**Comment by SeriousHoax** [comment]
Hmm I've disabled all the similar settings from that add-on and letting your add-on do all the things. You may close this issue now.

**Comment by kkapsner** [comment]
Great.
