### ISSUE TITLE
Blocking remote fonts with ublock origin breaks data url protection

### ISSUE THREAD

**Issue by array7** [kkapsner/CanvasBlocker#320]
tested on clean firefox 60.3-60.6
cb doesnt block data url when block remote fonts is enabled in ublock origin, otherwise everything is good.
ticking and unticking block data url pages fixed the problem . blocking font with no script works fine

i tested the bug here https://canvasblocker.kkapsner.de/test/dataUrlTest.php

**Comment by array7** [comment]
maybe you could make cb automatically tick and untick block data url pages in the background to fix the problem?

**Comment by kkapsner** [comment]
This is a race condition. You can have either font blocking from ublock or data url blocking from CB. This is Firefox problem (see #214 for more details).
The addon that loads the last wins the race in this situation (technical detail: it overwrites the changes for CSP-headers that the previous addons make). NoScript tries do be the last there (https://github.com/hackademix/noscript/issues/6) and that's why it works there.

I personally think that CB is less important in this case so you can disable and reenable ublock to put it at the end.
