### ISSUE TITLE
Question: Where would you recommend whitelisting?

### ISSUE THREAD

**Issue by rugabunda** [kkapsner/CanvasBlocker#393]
I see this option is an important one, its built into the system, but I see little to no documentation or comments on here that suggest when and where this would be useful. I would assume it is useful for websites one actually logs into. What are your thoughts?

**Comment by kkapsner** [comment]
Some pages just do not work properly when they are not whitelisted (e.g. if you use a webpage that does some image manipulation).
Also games can have a very bad FPS with CB.

I would only whitelist a page when you face problems. (I only whitelisted a page for the window API as reCaptcha is not working otherwise.)

**Comment by rugabunda** [comment]
Thank you!!!

**Comment by kkapsner** [comment]
You're welcome.
