### ISSUE TITLE
UA spoofing

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [kkapsner/CanvasBlocker#411]
AFAIK chromium browsers don't report
 - buildID
 - oscpu

They should return `undefined`. At least chrome and opera on my windows machines report that. Using current CB from AMO.

**Comment by kkapsner** [comment]
Yes - these two properties are Firefox specific. But there are easy ways to see if a browser is chromium or gecko based that do not include the navigator object. (E.g. ```Object.getOwnPropertyDescriptor(document.body.style.__proto__, "MozPaddingEnd");``` or any other vendor prefixed css property).
Also there is a difference in a property being set to ```undefined``` and being not present. So I would have to remove the property completely - but then we would have the situation of inconsistent data.

That's why I always thought that changing the UA to a different browser is kind of a waste of time (and that's why it was so late to CB). I introduced it completely for myself as I want to change the OS reported in the UA (I think there are still other ways to detect them but they are not that easy).

So what's exactly your point? That these settings should return ```undefined``` in the non Firefox navigator presets?

**Comment by Thorin-Oakenpants** [comment]
> So what's exactly your point? ...

pretty much that. just that the spoof should be plausible as any slip up means it's basically unique

I wondered about the "difference in a property being set to undefined and being not present": the code `x = navigator.abc` just returns undefined in chrome. But I know what you mean, I just don't quite follow how that applies in this case (obviously I'm missing something: but then again, I'm just not into chrome that much :) .. I guess one is a string and the other a property?

IDK why you wanted to expose the UA spoofing to the general population - I've always said it is a waste of time (preaching it for at least 5 years), and even convinced gorhill to drop it from uMatrix (or it may have been uBO, I forget)

Don't get me wrong: I think spoofing has it's place to fix compat issues, and for testing etc.

---

Anyway, I see two levels here. The first are the basics that most FP scripts would use (ua header, js nav properties) - and that's all I was pointing out :)

The second are the information paradoxes (as you already pointed out, and as TZP can already so; browser, version, os, and sometimes the architecture via other unbeatable means). Even RFP can't hide those - and everyone who spoofs is going to be in that same boat depending on their real values.

**Comment by kkapsner** [comment]
There are two points why I exposed it to the general population:
1. people will do it. Whatever you say. As the existing webExtensions do not protect properly (it's hard as you saw with your new attack vector) and CB has better protection (being FF only helps a lot here) I added it.
2. RFP sometimes produces inconsistent properties (e.g. on Linux the UA on the server site is not the same as on the client site). This can be fixed with that.

**Comment by spodermenpls** [comment]
> I think spoofing has it's place to fix compat issues
And circumventing shitty, otherwise unchangeable, Twitter re-designs, without the need to add another dedicated add-on.

**Comment by Thorin-Oakenpants** [comment]
> RFP sometimes produces inconsistent properties

That's by design for now. As long as it doesn't break sites, it's all good.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.15-RC1

**Comment by kkapsner** [comment]
Version 1.0 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0
