### ISSUE TITLE
Firefox version compatibility listed in add on page disagrees with manifest.json?

### ISSUE THREAD

**Issue by fsharpn00b** [kkapsner/CanvasBlocker#446]
## Description
In the description for version 1.1 (for example), it says:

https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/versions/
Version 1.1
Released Jan 28, 2020 - 301.47 KB
Works with firefox 56.0 and later, android 57.0 and later

However, if I unzip the .xpi and look at manifest.json, it says:
```
	"applications": {
		"gecko": {
			"id": "CanvasBlocker@kkapsner.de",
			"strict_min_version": "68.0"
		}
	},
```

I noticed this because I am running Waterfox 2019.10, which I believe has internal version number 56.3 (from looking at compatibility.ini in my Waterfox user profile).

As a result, I am able to install CanvasBlocker 1.1 because the add on page believes it requires only FF/WF version 56. However, WF then logs the following to the terminal:
```
1582821379200   addons.xpi      WARN    Add-on CanvasBlocker@kkapsner.de is not compatible with application version.
```

This discrepancy shows up in other versions as well.

The description for version 0.5.9.1 says "Works with firefox 56.0 and later, android 57.0 and later". However its manifest.json file contains `"strict_min_version": "57.0"`. If I install this into my Waterfox (56.3) I again get the compatibility warning.

The description for version 0.5.9 says "Works with firefox 52.0 and later, android 52.0 and later". This matches its manifest.json, which contains `"strict_min_version": "52.0"`. If I install this, I do not get the compatibility warning.

Please let me know if I can provide any additional information.
Thank you!

## Your Environment

* CanvasBlocker Version used: 1.1
* Firefox version incl. 32- or 64-bit: Waterfox 2019.10 (56.3) (64-bit)
* Operating System and version (desktop or mobile): Antix

## Your Settings
(default CanvasBlocker settings)

**Comment by kkapsner** [comment]
The AMO listing is changed to that lower version only to support Waterfox and the code of CanvasBlocker is designed to work there as well (but some features/functionalities may not work on the same quality - e.g. https://canvasblocker.kkapsner.de/test/settingsLoading.php). On my Waterfox (2020.02.1) I can install CanvasBlocker without any problems and also do not get any warnings.

For Firefox I test on three versions: ESR, release and nightly. This is reflected by the manifest.json as there I put the ESR version. The main reason is that I use some APIs that are not available in older versions of Firefox which reports me warnings when uploading a new version to AMO. The usage of that APIs are guarded so that CB does not break if they are not present.

**Comment by fsharpn00b** [comment]
Thank you for your reply. There must be something else in my setup that's causing it to issue that warning. I'll keep experimenting with it.

Quick question - are you using Waterfox classic or current? I'm using classic, so maybe that's part of my problem.

**Comment by kkapsner** [comment]
I'm also using Waterfox classic (it also stated version 56.3 in the compatibilty.ini).
