### ISSUE TITLE
Web Browser Features Detection test stays the same

### ISSUE THREAD

**Issue by GeorgN342** [kkapsner/CanvasBlocker#487]
Hey ! 

The tool is great helps me to improve me privacy but i have an issue:
I used the tool on two differnt browsers and at a Web Browser Features Detection test my Feature hash was the same .
How can this issue be fixed?
At other test like a canvas fingerprinting test it allways shows a differnt value. 

Thank yoou for your help!

**Comment by kkapsner** [comment]
Which web browser feature detection test are you using?

But in the default settings CB does not change the available browser features as this can lead to easier fingerprinting (the standard set of features of a browser is only dependent on the version and if you change that the mismatch can be detected and fingerprinted).

**Comment by GeorgN342** [comment]
I use browserleaks: https://browserleaks.com/
So what should i do i want to improve my browser privacy and that is the only big point left.

**Comment by kkapsner** [comment]
Changing this hash would not improve your privacy but reduce it. As far as I see it should only be dependent on your browser, browser version and OS. All of those are fairly easy to get.

So if you would not match the standard value for your setup you can easily be tracked because very few people do that. On the other hand if you do not change it you share the hash with many other people.

My advice is to leave this hash as is.
