### ISSUE TITLE
Addon does not prevent fingerprinting on EFF's "coveryourtracks" testpage

### ISSUE THREAD

**Issue by no-trick-pony** [kkapsner/CanvasBlocker#520]
On EFFs testsite for tracking and fingerprinting, Firefox does not clear the fingerprinting test with many real values unaltered with the plugin enabled even with "maximum protection" setting enabled.

## Expected Behavior
Fields/Values read should be random, at least for the page.

## Current Behavior
Many values can be read unchanged. CanvasBlocker only shows two "protection succesful" messages for "canvas" and "audio".
I see my real values for example for

- User Agent
- HTTP_ACCEPT Headers
- Time Zone Offset
- Time Zone
- Screen Size and Color Depth
- System Fonts
- WebGL Vendor & Renderer
- Language
- Platform
- Hardware Concurrency

## Steps to Reproduce (for bugs)
1. https://coveryourtracks.eff.org/
2. Do the test
3. See the results for the fingerprinting on the result page

## Your Environment

* CanvasBlocker Version used: 1.4
* Firefox version incl. 32- or 64-bit: 84.0.2 (64-bit)
* Operating System and version (desktop or mobile): Xubuntu 18.04
* Installed addons: uBlock Origin, Ghostery, Privacy Badger, Tampermonkey

**Comment by Thorin-Oakenpants** [comment]
Randomizing is not something that is a magic bullet: for almost all metrics, when it is spoofed or randomized, it can be detected as either a lie, or the fact that it is randomized
- if it can detect that it is a lie, that's cool, because it can't get the real value
- if it can detect that it is random, then that's **_no better_** than actually just returning a static spoofed value: but of course this still protects the real value

So long story short, randomizing is really only useful for fooling naive scripts. The more things you randomize, the slightly better chances of fooling a script. In reality, the real solution is make sure that the real values don't leak

Now, with that said: there is a **_compat cost_**. And each metric needs to be looked at on it's own. for example
- randomizing canvas in RFP (because it just totally scrambles the entire thing), breaks things: the canvas returned is unusable, but if you randomize it just a little (some random pixels, some random rgb channels, only change values by 1 or 2), then the canvas returned is usable
- but now randomize your timezone: one day you go to gmail and it thinks you're in America/Bogota .. the next time you're in Africa/Nairobe  .. then Asia/Kuwait .. etc. You gmail timestamps will be all over the place: sure, you could whitelist gmail in this case: but as a general startegy, randomizing timezones is not practical
- now consider randomizing languages: one way here is to always ensure that the first language is what you actually are, otherwise some sites will start serving up pages in languages you don't know: e.g. emphasis mine
   - e.g. https : // addons.mozilla.org/**_en-US_**/about (english)
   - e.g. https : // addons.mozilla.org/**fr**/about (french)
   - so consider that secondary language(s) are ignored, the randomizing is easily ignored
- randomize the platform: this **_will_** lead to some breakage and weird results. Note that you **_CANNOT_** hide your major platform (windows, android, linux, mac) and trying to spoof as something else just causes problems
- so much more but lets stop here
- user agent: easily exposed: kkapsner knows what I'm talking about: about the only thing this is good for is spoofing on specific websites for compat

And this is even assuming that web extension APIs are capable of successfully spoofing/randomizing: Answer: **_they're not_** as a general rule: but each metric needs to be looked at on it's own. There are many ways to get the real values, or to expose the equivalency elsewhere

---
web extension vs a decent script
- timezone and timezone offsets = 99% sure this is impossible to pull off
- language = AFAICT this is impossible: just think of all the formatting, `Intl` APIs, collation, and loads more
- languages = i.e secondary languages: this is nice!! I like this, it's what Brave have been suggesting as an extra fuck you to naive scripts
- fonts: do not go there .. do you have any idea of how many methods can be used to FP fonts? You just can't do it. And on top of that, it's likely to break things

---

### RFP

i.e baked into the engine core and handled properly

You already have timezone, timezone offsets, language (non `en*` builds but you can still set this in those), user agent, fonts (non-android), screen (which reports the inner window size: so stick to the startup size: but feel free to maximize for your threat model or tweak letterboxing), color depth, hardware concurrency, and so many more ... **are already there for you** to use .. behind a single pref


---

### last word

do not believe the entropy BS from sites like cover your tracks, amiunique etc - see [here](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#small_orange_diamond-%EF%B8%8F-anti-fingerprinting-extensions-fk-no) and scroll down to why the entropy figures are a load of rubbish

It only makes sense if you look at what a subset does: subsets like Firefox windows users, or Firefox Android users: because you will never hide those facts

/ end of War & Peace draft

**Comment by Thorin-Oakenpants** [comment]
here, just to prove a point ... from someone way smarter than me ...  https://abrahamjuliot.github.io/creepjs/tests/prototype.html

**Comment by crssi** [comment]
Nice one.
56 lies, all coming from CB.

**Comment by eric15342335** [comment]
i tried this recently https://fingerprintjs.com/demo/

**Comment by kkapsner** [comment]
User agent can be changed but has to be enabled manually in the settings (it's the navigator API). Since user agent spoofing is very tricky and can lead to being more trackable it cannot be done automatically.

The screen size is protected by default. If you see your real values there it means that you have a very common screen resolution and are not trackable over this.

WebGL vendor and renderer have to be configured manually.

Time Zone (Offset): it's very complex (#464) and I'm also not sure if it can be faked completely.

System Fonts: see #200 for more information about that.

Color Depth: may be fakeable but I don't think there is much entropy in this.

Language: could be worth a look to change the language*s* - if you want to fake your main language you should install Firefox in a more used language (e.g. en-US).

HTTP_ACCEPT Headers: I think you refer to the language part there. This can be changed in about:config. But if this is not the correct value you will be served pages in "wrong" languages. If you then change the language manually you are more trackable.

Platform: don't bother. It cannot be hidden which platform you use.

Hardware Concurrency: I don't think this can be faked.

> 56 lies, all coming from CB.

I think I can get rid of all but 1... and it's Mozilla's fault ;)

**Comment by crssi** [comment]
@kkapsner, just to clear it out... it was not meant as criticism.
Thank you for your hard works. ❤️
