### ISSUE TITLE
[Suggestion] Please add toggle switch to enable/disable addon

### ISSUE THREAD

**Issue by 4DEATH** [kkapsner/CanvasBlocker#535]
## Description
Usefull change/improvement when addon blocks/breaks certain websites. You could also add fast whitelist button which would do basically same thing.

## Expected Behavior
Click Addon icon
Click toggle switch to disable addon
When you are done, click same switch to enable addon

## Current Behavior
Click addon icon
Click settings
Change Block mode to allow everything
When you are done, go to same place to restore your block setting

OR

Go to addons page
Disable addon
When you are done, go to same place and enable addon

## Possible Solution
Toggle switch button in addon quick access menu
Whitelist button in addon quick access menu

## Context
Addon breaks most popular Turkish shopping website's login page (Hepsiburada.com) with "fake - non persistent" mode (which is default mode i think?)

## Your Environment

* CanvasBlocker Version used: 1.5
* Firefox version incl. 32- or 64-bit: 86.0 x64
* Operating System and version (desktop or mobile): Windows 10 x64 20H2 (19042.804)
* Installed addons: Ublock Origin, Canvas Fingerprint Defender, ClearURLs, LocalCDN, Privacy Badger and other probably irrelevant addons.

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": [DELETED],
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": false,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "16",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment]
There is already a way to whitelist a domain with the icon in the address bar. But there you cannot "unwhitelist" and the icon is not visible for some users (I think it's a browser setting). So adding a dedicated button in the toolbar icon is a good idea.

**Comment by spodermenpls** [comment]
@kkapsner I switched to the new Beta, and I noticed obviously the newly introduced "on/off switch" in the toolbar menu. It works (except for the [German] translation, since it's still "on/off" being displayed..), but I'm not totally sold on the icon design pattern. Using the green icon for "nothing tampered" (in the toolbar) and "active, regardless if something was tampered or not" (after a click on the toolbar badge, opening the menu) at the same time is kind of confusing, using those generic icons also don't make it clear that you can interact with them ("click" for switching between on or off). 
Therefore, I've dusted off my Illustrator CS5 and did some recoloring (using the same color as the power button of uBlock Origin, which seems fitting to me), and added two separate symbols, that indicate to the user a bit more cleary what the purpose of this button is. Since Github doesn't support svg-files in here, I've uploaded them under this link: https://workupload.com/archive/XZPPqkmc .

Reminiscent of uBlock Origin, a reload button next to the on/off switch (after one changes the mode on an already opened site) would be helpful too.

I also noticed on the two source SVGs, which I used for the two icons above, that there are two unused symbols next to the actual icon, do they have some purpose or do you maybe want to look through your icon library and delete those apparent leftovers from crafting them four years ago?
![browseraction-notprinted](https://user-images.githubusercontent.com/23747593/121526122-64327480-c9f9-11eb-8dbc-3d28add988f6.JPG)

**Comment by kkapsner** [comment]
The icons look great. Will use them.

I already thought about a reload button. Let's see how to incorporate it.

Also cleaned up the other svg files.

**Comment by kkapsner** [comment]
@spodermenpls check out the latest alpha.

**Comment by spodermenpls** [comment]
@kkapsner Very glad to hear that you like them. I checked the new version and the added symbols turned out pretty small, as expected, I made them a bit larger and gave them green and red color, with a little contour around the edges: https://workupload.com/archive/yAmmwGVz . 

Only thing leaving room for improvement on your side is probably the reload button, whose positioning is too far from the icon and not centered.

**Comment by kkapsner** [comment]
I found the coloured marks hard to see on the busy background so I gave the small circle a white background:
![grafik](https://user-images.githubusercontent.com/1105157/121818576-55adbc80-cc88-11eb-8789-cc366467eeb1.png)
![grafik](https://user-images.githubusercontent.com/1105157/121818577-59414380-cc88-11eb-9403-8c2ff6fced3e.png)

**Comment by kkapsner** [comment]
New alpha.

**Comment by spodermenpls** [comment]
> I found the coloured marks hard to see on the busy background so I gave the small circle a white background:

Yes, that's even better, I like it. The new alpha contains still my "first gen" icons, though?

**Comment by kkapsner** [comment]
Version 1.6 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.6
