### ISSUE TITLE
Removing a white listed site?

### ISSUE THREAD

**Issue by Jerriy** [kkapsner/CanvasBlocker#552]
Despite being whitelisted the website is not found in any of the multiple whitelist lists inside setting. Further down in the settings the "inspect whitelist" button, once clicked, displays the website  and a dropdown unticking the boxes provides no removal of the website. Instead the website remains in there with all the api boxes unticked. Are we supposed to untick the boxes and then press refresh or what?  There is no information anywhere how to undo or remove a site from being white listed. Typing "remove whitelist" in the search box brings up zero information. 

Outside settings, the menu in the addon's browser icon only notifies that the API's on the site on that tab has been whitelisted. Clicking anywhere provides no recourse.

Forcing me to do the only thing: reset (which defeats the purpose. I want to adjust the addon per site. 

Are we supposed to start spending an egregious amount of time just to find out this most basic of functions? Or is the addon designed to be reset after every visit of a site?

**Comment by kkapsner** [comment]
The "inspect whitelist" shows which API protections are active for a given URL/domain. So if you tick all boxes the whitelisting is removed. (In the next version there will be a description because it's not obvious: https://github.com/kkapsner/CanvasBlocker/commit/32af464c05eb10e5fbf128ce9bcc00f6575410a0)
Also the browser action will get a whitelist toggle: #535 

You do not have to reset - if you messed up your configuration you can either restore a saved version or modify the settings directly with the "Inspect" button in the "Export settings" (look at the urlSettings).

PS: why so angry?

**Comment by Jerriy** [comment]
I'm not "angry" just inconvenienced (because your settings have too many things "hidden" by default). Like for example my added websites listed in the various API's. 

Going to settings is not supposed to be a" treasure hunt" experience for the user.  But I'm not complaining. This is a free app and I'm grateful you took time to make it.

**Comment by kkapsner** [comment]
I know the settings can be a little bit overwhelming. That's why some things are not displayed by default.

> X means remove close shut etc, not "toggle".

It does remove the setting and does not toggle. The URL is just still shown to help to manage multiple specific settings for one domain.

I'm no UI/UX person and appreciate every help in improving it. So if you have something specific (image, good description, or even code) - let me know and we can discuss if and how it can be incorporated.
