### ISSUE TITLE
 CanvasBlocker obsolete with recent Firefox versions?

### ISSUE THREAD

**Issue by rvtzhrthbrtvzhrt** [kkapsner/CanvasBlocker#579]
Hi, according to https://github.com/nodiscc/user.js/commit/019974948e3f2649a0ebe4295ff202728388f3ea `canvas fingerprinting prevention is now available natively in firefox` (and they removed CanvasBlocker). Is CanvasBlocker really obsolete now?

**Comment by Thorin-Oakenpants** [comment]
The only "native" canvas protection in Firefox, for now, is via RFP (`privacy.resistFingerprinting`). Canvas is randomized, totally unusable - it does per execution because it is fast and easy and fools naive scripts, and cannot be averaged or bypassed. You can tell if it's RFP because the images look patterned

For sites that NEED canvas, you can click on the canvas icon in the url bar and allow permanently or for the session. This does not compromise your fingerprint, and it won't be used to link all your traffic because
- one, it's not all sites
- two: it's only one metric
- three: canvas alone, depending on the canvas being tested, is usually equivalency
- four: not all excepted sites use the same canvas test
- five: not all excepted sites share FP data
- six: if it's a site you log into all the time, you're already ID'ed (as a repeat visitor)
- seven: is it even being used to FP you?

RFP covers a lot more than just canvas.  If RFP isn't for you, for whatever reason (e.g. it sets your timezone as UTC0, it forces prefers-color as light, sometimes alt keys don't work, etc), then your only option is to use Canvas Blocker. All other Firefox canvas extensions are not up to scratch, AFAIK (most are downright useless). Extensions are not totally immune - e.g. canvas can still leak via service workers - this is not the extensions fault.

You can use CB with RFP. RFP doesn't release canvas to extensions, when it protects them. But if you allow a site exception, then CB will kick in and randomize the canvas, subtlely. And if that doesn't work, you can still whitelist the site in CB, noting that this does not compromise your fingerprint - see the seven items above

I guess nodiscc's comment meant that native protection was available by default in the user.js

Feel free to close

**Comment by kkapsner** [comment]
I have very little to add to that. Only that CanvasBlocker is not only about Canvas but also other fingerprinting attacks.
