### ISSUE TITLE
known pixel value test 10: API tampering detected

### ISSUE THREAD

**Issue by CocaineJohnsson** [kkapsner/CanvasBlocker#593]
## Description
https://canvasblocker.kkapsner.de/test/detectionTest.html

Fails known pixel value test 10 on firefox 96.0.2 under linux with all other addons disabled, in a brand new profile using both stock settings of CanvasBlocker and stock firefox settings. 

## Expected Behavior
I'd expect all the tests to pass.

## Current Behavior
known pixel value test 10: API tampering detected
![Screenshot_2022-01-24_12-40-45](https://user-images.githubusercontent.com/53689060/150776764-af8fb572-6ab7-4758-99ac-2ad00393396c.png)

## Steps to Reproduce (for bugs)
1. Run arch linux with an nvidia gpu (and a ryzen 7 2xxx processor, if somehow relevant)
2. Run firefox 95.x or 96.x (haven't tested older versions due to the effort involved)
3. Run the detection test
4. The test should fail

## Context
It's not really a major problem, it may compromise tracking protection marginally for some websites.

It still happens in a fresh profile as mentioned.

## Your Environment
* CanvasBlocker Version used: 1.7
* Firefox version incl. 32- or 64-bit: 96.0.2 (64-bit)
* Operating System and version (desktop or mobile): Arch Linux 5-15.10
* Installed addons: None, other than canvasblocker since I tested in a fresh profile

## Your Settings
Factory default CanvasBlocker settings.

**Comment by kkapsner** [comment]
This is expected behaviour and it's intentional that this test fails in the default settings. It shows the limitation of CanvasBlocker and I do not want to pretend that CanvasBlocker is not detectable at all. It changes things - therefore it's detectable.

The test does not fail if you use the stealth preset (or set the protected canvas part to "input" - this is not the default because it has a huge performance impact).

You can find further information on this topic in #114 and #316.
