### ISSUE TITLE
Question regarding Fingerprinting (no issue!)

### ISSUE THREAD

**Issue by FrostBlade5** [kkapsner/CanvasBlocker#611]
This is not an issue but more like a question.
I did multiple "privacy tests" regarding fingerprinting on many different websites, i have decent setting for privacy now, however there are a few specific tracking methods that appear to make my browser pretty unique.

The screenshots below will show exactly what i'm talking about.
I like CanvasBlocker alot so i tought maybe i can ask the developer if he is aware of a solution to block or fake the below tracking/printing methods?

![5](https://user-images.githubusercontent.com/91756004/164878061-8626ea51-9ce8-4396-a674-e054e222a2a1.png)
![4](https://user-images.githubusercontent.com/91756004/164878062-ff453c32-125c-4f97-bd30-dd91702daea4.png)
![3](https://user-images.githubusercontent.com/91756004/164878063-a81f0d12-aadd-424a-9ace-afb6bfa6b2dc.png)
![2](https://user-images.githubusercontent.com/91756004/164878064-8e351b70-bad0-49a2-937c-acef1ea1e881.png)
![1](https://user-images.githubusercontent.com/91756004/164878065-df6e076a-e77c-4b9e-a756-30e145bcaa79.png)

As a note, when i did those test i was using privacy.resist.fingerprinting with firefox and also used the default canvasblocker settings (fake mode).

**Comment by kkapsner** [comment]
Having a unique fingerprint is not a problem by itself: https://canvasblocker.kkapsner.de/faq/#uniqueFingerprint
With CB in the default settings the audio and canvas fingerprints are unique but should change.

I do not know what the "Media device" fingerprint is exactly. Which page were you using?

Font fingerprinting was often suggested here (e.g. #200) and should be handled upstream in Firefox itself. And 1 in 21.68 is not too bad.

**Comment by Thorin-Oakenpants** [comment]
> I do not know what the "Media device" fingerprint is exactly. Which page were you using?

kkapsner -> https://amiunique.org/fp -> AFAICT it's not effective: it's incorporating the uuid's (which are randomized in gecko on a per eTLD+1, per session, and I think per tab request)

You can see this when if you turn on RFP and do a test, and check uniqueness for all time - it will say you are unique (1 audio, 1 video), which is clearly bollocks because not only have I tested that probably several hundred times over the last year or so (i.e the whole test with RFP on), but numerous others have too (i.e with RFP - which controls the number and type and name of media devices - which only leaves the uuid AFAICT)

> fonts

for windows, that's actually not a great result. If you use RFP's font vis protection, it reduces Win7 to about 3 results, and Win10 to about 3 results (maybe less, it's not a very comprehensive test, e.g. if you added `HoloLens MDL2 Assets` that would create more Win10 buckets)

Win7 for me is about 1 in 12.25 as an example

PS: at least fourteen methods to detect your fonts .. and counting - this is beyond the scope of an extension as kkapsner says. The only way to do it is to actually limit the fonts available to web content (and have them, you can't make a missing font be detected) within the browser code

> entropy

@FrostBlade5  - these entropy figures not reliable. test sites like this are great for seeing what is returned, but the datasets are not real world and are tainted by the nature of those visiting who repeat and tinker and pollute the results (and they create self-fulfilling prophesies that drive down entropy figures to the point of being clearly silly - e.g. coveryourtracks 1 in 6.x people are timezone name `UTC` which is just ridiculous). And they make no sense when in reality you should be looking at smaller sets that can't be obscured - it makes no sense to pollute the entropy figures for desktop screen measurements with all the android ones

i'll stop there

**Comment by kkapsner** [comment]
@Thorin-Oakenpants: thanks for the input. I think the question is then answered.
