### ISSUE TITLE
Breaks GNU Social account profile background preview

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#62]
> The image looks really awful. As you can see the colour gradients are not displayed correctly and it seems as if the colour depth would be too low to display them. However when saving the picture it looks good - only the preview looks like this. [...]
> 
![gif](https://gnusocial.de/attachments/140041a6902cb8f86eed638d25fb3e1fad3d99cced8f4fe8f62abbd624db6c21.gif)

and

> So when I set `^https://gnusocial\.de/rugk$` on the whitelist of canvasblocker it works.

See this error report for details: https://git.gnu.io/h2p/Qvitter/issues/32

CanvasBlocker is set to "Fake readout API".

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah that happens on twitter and other sites too. its only for the preview. just whitelist it if it matters to you. i personally add the domains to the ignore list because i dont care

**Comment by kkapsner** [comment]
I guess the Image has to be read somehow to be displayed and to calculate some properties. This triggers the faking which is quite slow on big images.

If the faked image data is used to display something the little changes that are made may also look "awful". If you look at https://www.browserleaks.com/canvas there the plain orange field is disturbed (you may have to zoom in to see it).

**Comment by rugk** [comment]
Mhh, okay. Is there any way to display the image correctly without allowing the site to read the Canvas?
Can you probably display the correct Canvas on top of the broken one (without letting the website access this image)?

If not then I'd suggest to at least add this issue as a "know bug" or something like this, so that users know it can cause this.

**Comment by berrythesoftwarecodeprogrammar** [comment]
is it really a bug? i thought that was the intended behaviour? if you want it to display correctly then you whitelist it

**Comment by rugk** [comment]
Generally the intended behaviour is to block the readout API (which can be used to track users). IMO this is not reading out a Canvas, it is displaying it. So even if the source file is a image it is rather a "read-in" process as the image file is converted to a Canvas, whcih is displayed.
So this addon should only block the tracking part...

**Comment by kkapsner** [comment]
No, there is no way to display the image correctly if the site uses data that is read from another canvas to display the image.

And this is not a bug. It's how the faking works. It disturbes the image a little bit so that the hashes do change every time.

If you want to block the readout API you should use the "block readout"-mode instead.

This page does use one of the readout functions so it will get the disturbed data - otherwise you would not get a notification...

Since the exact ways to track can be very different (and my spare time is limited) I go with the save way of disturbing everything and not trying to guess if the use is legit or not. If you think a page should see the undisturbed data you can whitelist the site or the script.

**Comment by rugk** [comment]
Okay, so from the dev perspective this may makes sense, but from the user perspective it is, say... at least surprising. So what about adding this information to the Readme?
