### ISSUE TITLE
CanvasBlocker DOMRect API detections

### ISSUE THREAD

**Issue by kntjspr** [kkapsner/CanvasBlocker#620]
## Description

https://arkenfox.github.io/TZP/tests/domrectspoof.html
DOMRect API 
![image](https://user-images.githubusercontent.com/65537922/167419244-897726f5-5e31-4032-b70a-99cee5611fc5.png)

## Steps to Reproduce (for bugs)

1. Turn on DOMRect Spoof 
2. Visit https://arkenfox.github.io/TZP/tests/domrectspoof.html
3. Will return fail

Code: https://github.com/arkenfox/TZP/blob/master/tests/domrectspoof.html
Repo: https://github.com/arkenfox/TZP

## Context
DOMRect API are easily detected when spoofed
## Your Environment

* CanvasBlocker Version used: 1.8
* Firefox version incl. 32- or 64-bit: 64
* Operating System and version (desktop or mobile): desktop
* Installed addons: Canvasblocker, Bitwarden

## Your Settings
~~~ json
{
	"logLevel": 1,
	"urlSettings": [
		{
		
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"blockDataURLs": true,
		"protectDOMRect": false,
		"protectTextMetrics": false
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "input",
	"minFakeSize": 1,
	"maxFakeSize": 1000000,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{\"shared://domain\":[239,254,228,88,242,160,197,171,33,43,1,123,123,180,70,177,29,14,166,183,96,226,47,170,239,3,33,95,255,71,9,176,179,71,244,111,216,31,196,27,253,185,6,176,116,170,88,125,97,90,180,66,180,210,62,11,55,43,252,35,140,144,244,203,11,222,216,119,199,118,157,9,93,245,126,145,94,161,178,124,81,176,254,24,30,111,52,171,45,48,102,189,0,177,132,71,192,50,147,108,224,50,50,25,77,40,62,138,94,100,74,148,240,162,117,95,125,4,12,185,227,80,15,124,177,223,184,166]}",
	"persistentIncognitoRndStorage": "{\"firefox-private@shared://domain\":[29,91,27,78,101,188,224,24,10,47,172,228,210,196,211,75,113,191,5,192,30,29,205,75,27,241,221,205,253,32,39,99,208,12,31,92,201,128,139,78,49,29,122,92,77,120,51,20,41,202,69,34,159,242,8,52,94,136,133,4,74,36,19,99,48,212,246,120,68,241,107,82,1,158,123,238,158,249,1,43,113,247,58,80,22,148,186,50,116,254,201,90,135,8,82,136,213,149,69,109,131,163,214,95,154,234,15,157,96,200,223,30,47,43,223,147,167,30,93,83,193,128,110,217,141,18,151,41]}",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1652101103718,
	"sharePersistentRndBetweenDomains": true,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "13",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 2,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
~~~

**Comment by kntjspr** [comment]
More info, maybe it will help: https://abrahamjuliot.github.io/creepjs/tests/domrect.html

**Comment by Thorin-Oakenpants** [comment]
that PoC isn't even finished, I should do that .. and it's not the only method (I also have a shift method which exposes it). This is a known value test, and extensions cannot bypass those (short of blocking the API) - same as known pixel tests for canvas. You cannot beat mathematical proofs, not even built in browser solutions can, and you shouldn't expect extensions to either

The job of canvas blocker is to protect the real value by randomizing so scripts become naive (because a static lie is useless with no crowd) - if you don't know what that means, read [this](https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-fingerprinting) - detecting a lie is immaterial, protecting the real value is the aim

@kkapsner +1 closing when you're ready

**Comment by hkfsc** [comment]
> that PoC isn't even finished, I should do that .. and it's not the only method (I also have a shift method which exposes it). This is a known value test, and extensions cannot bypass those (short of blocking the API) - same as known pixel tests for canvas. You cannot beat mathematical proofs, not even built in browser solutions can, and you shouldn't expect extensions to either
> 
> The job of canvas blocker is to protect the real value by randomizing so scripts become naive (because a static lie is useless with no crowd) - if you don't know what that means, read [this](https://github.com/arkenfox/user.js/wiki/3.3-Overrides-%5BTo-RFP-or-Not%5D#-fingerprinting) - detecting a lie is immaterial, protecting the real value is the aim
> 
> @kkapsner +1 closing when you're ready

Hmm...if someone already known that you are lying, then you think they will trust the "real value" you faked can be the "real" one? This plugin is useless if it can be detected. if it can be detected, what's the meaning of you are faking the value to protect the real one? They can just mark you as `cavans=faked`, rather than record the faked value and just say "you are all the same because you are using this plugin, no differences!!!
**Then all the random value related works are meaningless at all.**
We should seeking the way which directly modify the firefox source code, rather than using any plugins with JS, I think it should be the final way to do the real "protection" for everyone.

**Comment by Thorin-Oakenpants** [comment]
> read [this](https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-fingerprinting)

READ. THE. LINK.

If it protects the real value then it doesn't matter how it does it. Not all scripts will bother to test for fake domrect - those that don't become naive (because it's randomized). Those that do test for fake domrect, still only get a single value (i.e untrustworthy) which is the same as reducing entropy (vs raising entropy) - it just happens to be that extensions don't have large crowds.

> Hmm...if someone already known that you are lying, then you think they will trust the "real value" you provided can be the "real" one?

No one said that. If it knows it is a lie, then it doesn't swallow the poison pill - i.e not naive

**Comment by hkfsc** [comment]
Already read the link you posted.
I think you just concluded that what this plugin's did are meaningless, because what it does "just same as the one who set the those value to empty", they all protected the "real value".
So? let's just remove the random related code of this plugin?

**Comment by Thorin-Oakenpants** [comment]
> I think you just concluded that what this plugin did are meaningless

don't think. read -> "Not all scripts will bother to test for fake domrect - those that don't become naive (because it's randomized)"

**Comment by hkfsc** [comment]
> > I think you just concluded that what this plugin did are meaningless
> 
> don't think. read -> "Not all scripts will bother to test for fake domrect - those that don't become naive (because it's randomized)"

Not all, what a naive assumption, do you know how many most well-known website all have those tests? Unless you are offline and just use some services like "no-one-will-use.com", rather than the services on Twitter, Google, Apple, etc.

**Comment by Thorin-Oakenpants** [comment]
I don't think you are following the logic here,

It doesn't matter what scripts are out there and what sites may or may not have for scripts. There are only two outcomes when randomizing. This is being as simplistic as I can get, as per the link. This is ignoring the fact that fingerprints are always loose/fuzzy and that the user is in a crowd or not, or that you are already unique doing nothing, or equivalency, or that the value can be leaked via other means, or extensions vs built-in solutions.

The more items randomized that a scripts checks for, the more the chance that at least on one of those, it doesn't detect a "lie" and it swallows a poison pill
- outcome one: you are unique per eTLD+1, per session (or per tab or whatever) = i.,e the FP doesn't link you
- outcome two: all metrics that are randomized are detected as a "lie" and recorded as a lie

The best an extension can do is outcome one, via randomizing. So what you're suggesting is that CB is 100% a waste of time, and that is clearly not true. Is it the best solution, no - but is it the only solution for many, yes.

**Comment by hkfsc** [comment]
> I don't think you are following the logic here,

Hmmm...if the plugin cant prevent outcome two, it will not enough or useless(meaningless) for most usage cases.

**Comment by Thorin-Oakenpants** [comment]
so all the cases where outcome one happens is not a net gain (and I will tell you now that doing nothing is just as bad as outcome two)? I suggest you think a bit more about it

**Comment by Thorin-Oakenpants** [comment]
Brave does a lot of randomizing (they call it farbling) .. and every single bit of it can be detected as a lie - are you telling me that Peter Synder is an idiot?

**Comment by Thorin-Oakenpants** [comment]
Mozilla also randomizes. RFP does this to canvas. That too can be detected. Are you also telling me that Tor Browser and Moz devs are idiots?

**Comment by kntjspr** [comment]
I think @hkfsc use-case is to make the script think that the user is naive or make it look like the user is not using any kind of anti fingerprinting techniques (lies) which is useful to avoid additional security checks (captcha for example) on logging in on your own bank account, school account etc. without having to completely whitelist the site and expose your fingerprints even though it's for "your own good". 

That's what I also thought after using CB that it's completely different from other popular anti-fingerprinting scripts (e.g Firefox RFP). I was wrong, there are ways to detect cb and every other anti-fp scripts as there was a the disclaimer on cb site.

Also let me add the fact that DOMRect will change after zooming in-out or dpi changes and it is quite unreliable when used as a fingerprint techniques. 

The purpose that I opened this issue is to find a way maybe to even out the odd dimensions (e.g changing y,top,bottom & height) in order to match with (x,left,right & width)
![image](https://user-images.githubusercontent.com/65537922/168430146-c7b2b198-f375-4453-bedc-bb7d21021b66.png)

I'm still not quite experienced in fingerprinting stuff and idk if it's possible that's why I opened the issue so @kkapsner could see if there's any workaround on it.

**Comment by hkfsc** [comment]
> Mozilla also randomizes. RFP does this to canvas. That too can be detected. Are you also telling me that Tor Browser and Moz devs are idiots?

Hmmm, I havent said they are idiots, but you are not following we I said, meaningless arguments with you , you can just continue post your meaningless ideas to ask author to close this issue, and keep use this plugin for login your bank accounts, personal accounts, I hope they will not detect anything with you, and you can be a free bird when you are online.

**Comment by Thorin-Oakenpants** [comment]
> Hmmm, I havent said

You have repeatedly said that if randomizing ican be detected then it is useless ... once again, it can **_all_** be detected, every single bit of it .. so there .. cogito ergo sum .. you are implying that the Brave, Tor Browser, Mozilla devs don't know what they are doing, and that the extension devs don't know what they're doing

The job of anti-fingerprinting is to protect the real value. Detecting lies doesn't matter except to distinguish naive vs advanced scripts. Since not all scripts are advanced, then there is a net gain. For advanced scripts, you need a crowd, so therefore extensions can only benefit by randomizing. How hard is this to understand?

Here's another fact. All lies, regardless of them being randomized, can still be detected as lies. So for example, when RFP spoofs hardwareConcurrency as `4`, this can be detected, and also returned as a "lie". How is that any different to detecting a random value? Detecting a lie is the same result regardless of the method used (excluding actually FPing the protection method).

By your logic, anything done to reduce entropy is a waste of time

**Comment by Thorin-Oakenpants** [comment]
@kntjspr 

I came up with that PoC. I just happened to use a square. I could just as easily use any transformed shape. The PoC is also specifically zoom resistant in gecko (and almost zoom resistant in blink, but I don;t care about blink or webkit). Changing any of the values will result in a lie. You can't just add from one and substract from the other

It also doesn't address the other method I came up, where I shift by 0.x px right and down and compare (the difference for all values should be 0.x), but because CB uses a random amount per value to deviate by, it's easily exposed

And all of these can be fingerprinted: i.e is it per execution or persistent, is it a variable amount or set amount to deviate (e.g. Chameleon gets a random amount to deviate by, but applies that same amount to all values), what amount is used (size bucketing), etc

You cannot beat a mathematical proof, which is why I came up with it

---

Everything is fluid in fingerprinting. FPs should always be treated as loose/fuzzy. Screen and window measurements, line-heights, canvas + webgl depending on what fonts are used if any, and many other things also change with zoom, DPI, devicePixelRatio, system scaling, layout.css.devPixelsPerPx - a lot of it is interconnected

But that doesn't mean they can't be collected and correlated, or indeed, reverse engineered to provide a stable value (e.g. screen can always be reversed to show native resolution - but not everything is linear). Screen metrics, despite changing with zoom etc, are heavily used to help link FPs

**Comment by kntjspr** [comment]
Got it, that sums everything up thanks! No wonder why it was showing neither passed or failed in tzp domrect test on other custom browsers like [GoLogin](https://gologin.com/).

One thing: I wonder what affects the DOMRect API fingerprint without changes in dimensions. It could be GPU?  Maybe If I'll modify GPU renderer capabilities would change that or maybe using Virtual machines, have u tried those possibilities? I feel like there's something noise that could be added in order to renew those values (don't wanna contaminate my identity).

As of the font-fingerprint, you can modify font lists on `about:config` I wonder If compiling a list of fonts and randomizing the list or changing the font metrics would work? or it is a bad idea?

You guys are great in this field; I was wondering whether you have any fingerprint discord communities? I'd love to talk about it because I've been playing with it for about 2 months.

**Comment by Thorin-Oakenpants** [comment]
I don't want to derail this topic. There is no "we" (as in you guys), so no discord/matrix/whatever .. it's just me, at TZP (I had a previous repo before the current one), which I started for my purposes (since I couldn't get a decent FP suite anywhere else) and kkapsner helped a bit, and then abraham (creepy) came along and because he's a JS wizard and speedy as F and I'm not, he built creepy which while it has a few differences such as purpose, it has a lot I always planned to add to TZP. Abraham and I talk and share.

I'm not really into discussing the rest of your questions, but the answer is there more than you think that can affect things. GPU won't affect domrect, but I can name things you haven't mentioned yet that will. And yes, GPU will affect other metrics. And fonts: you cannot lie about them - you either have them and allow them in web content, or you don't. The font whitelist pref is not fit for purpose (it is for Tor Browser) and RFP already has a solution for windows/mac and some linux. The whitelist pref is a global switch (so if you modify it, all tabs change) - what you're asking is more akin to what Brave does - which starts with an allowlist per OS (like RFP's kBaseFonts), bundles some extra fonts, and then allows random bundled fonts per eTLD. This is easily bypassed by excluding the list of bundled fonts if found. That still protects the user, because the allowlist reduces entropy as it is limited to system fonts that came with the OS. Anything more than that, e.g. trying to block random fonts per eLTD, will just result in breakage (tofu), because you need a bare minimum anyway, and that bare minimum is already the whitelist/allowlist

> I even just found out that user-agent changes can be detected by solving mathematical problems (PI^-100).

lols. really. I think you have that mixed up a little - it will expose an engine lie, not all user agent lies. have you never head of feature detection? check TZP's engine and version PoCs. You can't hide your OS (windows/linux/mac/android), engine, version, platform architecture, and often minor OS info (e.g. win7 vs win10, or various linux distros/DEs). Almost the entire user agent can already be bypassed. And a lot of other things you can't hide unless it is a built in browser solution, such as timezone, or language. 

Also, note, that TZP (work in progress) goes out of it's way to detect and show the lies and bypasses, but it doesn't have to. Those lies will manifest in the results in the fingerprint anyway (remember how FPs are fuzzy) - e.g. you claim to be windows 7 but you have windows 10 fonts. Any decent JS attack template type collections will expose these (Abraham does this a bit, but collecting hashes of known versions/platforms) and google's picasa FPing project did the same thing

lets just end this discussion .. or kkapsner will growl at us :)

**Comment by kntjspr** [comment]
I was referring to "you guys" as those person who created and contributed to TZP, CreepJS and CB I just thought that maybe they came from a single community cause they really work well with each other.

and as of the user-agent my bad, I phrased it badly, yes I meant the browser engine, you cant fake ua from chrome to firefox because they have a different engine, that's what came into my mind at that time🤣.

I will close this discussion since it is getting too far from DOMRect issue. Thanks for the info.

**Comment by Thorin-Oakenpants** [comment]
> I just thought that maybe they came from a single community cause they really work well with each other.

I know them both via my endeavors and they obviously have the same privacy passions as myself, and yup all three of us are at TZP, along with the dude from Chameleon from time to time. I'm probably the common thread here
