### ISSUE TITLE
block readout API: from 7.17 down to 2.42 (panopticlick)

### ISSUE THREAD

**Issue by hdatma** [kkapsner/CanvasBlocker#79]
CB's option "block readout API" returns an "undetermined" hash of canvas fingerprint in https://panopticlick.eff.org. This is bad, because of its 7.17 bits of identifying information. 

Try returning the hash "00000000000000000000000000000000" instead, because its
bits of identifying information are only 2.42.

**Comment by kkapsner** [comment]
The block mode returns no information. That's the whole point of this
mode: it blocks the use of canvas completely. Therefore the 7.17. bits
of information are wrong - it's only one bit: canvas can not be used.

Also the hash value is not in my hands since the website JS and not the
browser/addon JS produces it. I can only controll the input for the
hashing algorithm.

Am 01.09.2016 um 22:48 schrieb hdatma:
