### ISSUE TITLE
Compatibility with old FF versions

### ISSUE THREAD

**Issue by StnadardUsre** [kkapsner/CanvasBlocker#82]
Is it possible to modify the extension so it works with old FF versions, in particular - FF 7? I don't care about any GUI glitches, just need the default setting (fake readout API) to work out of the box. Tried to modify the minimum supported version in 'install.rdf', but, as expected, it doesn't work. Just need a hint or a small guidance.

**Comment by kkapsner** [comment]
I think it is possible but will be much work. Since I never worked with the addon-API for such an old FF I have no clue what to change. But for sure you will have to get rid of all the e10s stuff - i.e. having the frame-script an main-script separate.
Also you should check first if the SDK supports such an old FF.

So to conclude: I can not give you much of input to make it work in FF 7. And I also have no time to figure that out - sorry.
