### ISSUE TITLE
Slow PDF rendering

### ISSUE THREAD

**Issue by nkestrel** [kkapsner/CanvasBlocker#93]
Version: 0.3.4-Release on FF50
Example PDF: http://www.arlec.com.au/wp-content/files/MAL547.pdf

**Rendering time:**
Disabled: 3 seconds
Allow everything: 3 seconds
Fake readout API: 142 seconds
Block readout API: 10 minutes+ unresponsive

**Comment by kkapsner** [comment]
This is a really heavy PDF with big images (up to almost 6 000 000 pixels). Faking such huge amount of data takes some time. For the moment I would add a RegExp-Filter to the white list that allows PDF (\.pdf$). The perfect solution would be to use the maxSize-setting - but this is not as fast as it should be at the moment. The fix will be part of the next release.

Why the blocking makes the browser unresponsive is a little bit confusing to me - but I think there is nothing I can do about that.

**Comment by spodermenpls** [comment]
I ran now myself multiple times in big PDFs that were freezing Firefox for a long time due to CanvasBlocker starting to choke on the amount of data. Now with 0.3.5 available, I want to use the refreshed maxSize-function but I don't know what canvas sizes are normal, in the end I don't want to whitelist unintentionally Canvas's which wouldn't be a problem to fake. What do you think could be an appropriate value to type in the settings box? Maybe you should add the value as an example in the description text too, so users have a guideline which they can follow (the freezes with big PDFs are probably the last big inconvience with CB).

**Comment by kkapsner** [comment]
I think I would take something between 500 000 and 1 000 000. But this is just a gut feeling - I have no data how big fingerprinting canvas are.
You should definatelly not go under 10 000.

**Comment by spodermenpls** [comment]
I am testing with 1 000 000 right now, bigger PDFs are defin**itely** (typo above..) loading without a big delay or freeze now. The maximum "freeze free" size most likely depends on the hardware, so with my "above average" setup I probably won't have much trouble in the future with my new set limit.

**Comment by spodermenpls** [comment]
I noticed that with activated notifications, I still get the "faked readout" pop-up when CB has skipped the faked read-out due to size. Maybe "skipped readout" is an notification, that should be added to the next version?

**Comment by kkapsner** [comment]
I looked in the code and when skipped, no notification is triggered. Maybe there was some smaller canvas that triggered the notification.

The label for the ignore button is kind of tricky, because "ignore" alone could be interpreted like white listing. And "Do not display notifications for this domain" is just much too long.

But for the next version I will try out some different notification system which should have less space restrictions and then I can be more explinatory.

**Comment by spodermenpls** [comment]
I didn't had in mind that PDFs can contain multiple canvas's that don't have to be bigger than the set limit in every case. My bad. 😅

That's true. 
I noticed that the pop-up bar tends to lag when it opens itself with heavy duty pages beneath, maybe the new system will fasten things up a little bit. Normally I keep them deactivated anyway, so it doesn't bother me personally too much.
